--Database--

function checkIfExists(table, name)
 for k,v in pairs(table) do
  if (v.name == name) or (v == name) then --lulz lua powa
   print("Conflict (i.e elements appearing twice) detected when loading Database. Skipping the item.")
  return true
  end
 end
 return false
end

function checkIfFormulaExists(table, formula)
 for k,v in pairs(table) do
  if (v.formula == formula)  then
   print("Conflict (i.e formula appearing twice) detected when loading Database. Skipping formula.")
   return true
  end
 end
 return false
end

Categories = {}
Formulas = {}

function Cat(id,name,info)
 if checkIfExists(Categories, name) then
  print("Warning ! This category appears to exist already ! Adding anyway....")
 end
 return table.insert(Categories, id, {id=id, name=name, info=info, sub={}, varlink={}})
end

function CatVar(cid, var, info, unit)
 Categories[cid].varlink[var] = {unit=unit, info=info }
end

function sCat(cid, id, name, info)
 if checkIfExists(Categories[cid].sub, name) then
  print("Warning ! This subcategory appears to exist already ! Adding anyway....")
 end
 return table.insert(Categories[cid].sub, id, {category=cid, id=id, name=name, info=info, formulas={}, variables={}})
end

function aF(cid, sid, formula, variables) --add Formula
 local fr = {category=cid, sub=sid, formula=formula, variables=variables}
 --In times like this we are happy that inserting tables just inserts a reference
 --commented out this check because only the subcategory duplicates should be avoided, and not on the whole db.
  --if not checkIfFormulaExists(Formulas, fr.formula) then
   table.insert(Formulas, fr)
  --end
  if not checkIfFormulaExists(Categories[cid].sub[sid].formulas, fr.formula) then
   table.insert(Categories[cid].sub[sid].formulas, fr)
  end
 --This function might need to be merged with U(...)
 for variable,_ in pairs(variables) do
  Categories[cid].sub[sid].variables[variable] = true
 end
end

function U(...)
 local out = {}
 for i, p in ipairs({...}) do
  out[p] = true
 end
 return out
end

----------------------------------------------
-- Categories && Sub-Categories && Formulas --
----------------------------------------------

--Physics(electricity)
Cat(1, "Resistive Circuits", "Performs routine calculations of resistive circuits")

CatVar(1, "A", "Area", "m2")
CatVar(1, "G", "Conductance", "S")
CatVar(1, "I", "Current", "A")
CatVar(1, "Il", "Load current", "A")
CatVar(1, "Is", "Current source", "A")
CatVar(1, "len", "Length", "m")
CatVar(1, "P", "Power", "W")
CatVar(1, "Pmax", "Maximum power in load", "W")
CatVar(1, "R", "Resistance", g.omg[1])
CatVar(1, "Rl", "Load resistance", g.omg[1])
CatVar(1, "Rlm", "Match load resistance", g.omg[1])
CatVar(1, "RR1", "Resistance, T1", g.omg[1])
CatVar(1, "RR2", "Resistance, T2", g.omg[1])
CatVar(1, "Rs", "Source resistance", g.omg[1])
CatVar(1, "T1", "Temperature 1", "K")
CatVar(1, "T2", "Temperature 2", "K")
CatVar(1, "U", "Voltage", "V")
CatVar(1, "Vl", "Load voltage", "V")
CatVar(1, "Vs", "Source voltage", "V")
CatVar(1, g.al[2], "Temperature coefficient", "1/"..utf8(176).."K")
CatVar(1, g.rh[2], "Resistivity", g.omg[1].."*m")
CatVar(1, utf8(963), "Conductivity", "S/m")

sCat(1, 1, "Resistance Formulas", "")
aF(1, 1, "R=("..g.rh[2].."*len)/A",U("R",g.rh[2],"len","A") )
aF(1, 1, "G=("..g.si[2].."*A)/len",U("G",g.si[2],"len","A") )
aF(1, 1, "G=1/R", U("G","R"))
aF(1, 1, g.si[2].."=1/"..g.rh[2], U(g.si[2],c_P))

sCat(1, 2, "Ohm\'s Law and Power", "")
aF(1, 2, "U=I*R", U("R","U","I") )
aF(1, 2, "P=I*U", U("P","U","I") )
aF(1, 2, "P=(U*U)/R", U("P","U","R") )
aF(1, 2, "P=U*U*G", U("P","U","G") )
aF(1, 2, "R=1/G", U("R","G") )

sCat(1, 3, "Temperature Effect", "")
aF(1, 3, "RR2=RR1*(1+"..g.al[2].."*(T2-T1))", U("RR2","RR1","T1", "T2", g.al[2]) )

sCat(1, 4, "Maximum DC Power Transfer", "")
aF(1, 4, "Vl=(Vs*Rl)/(Rs+Rl)", U("Vl","Vs","Rl","Rs") )
aF(1, 4, "Il=Vs/(Rs+Rl)", U("Il","Rs","Rs","Rl") )
aF(1, 4, "P=Il*Vl", U("P","Il", "Vl") )
aF(1, 3, "Pmax=(Vs*Vs)/(4*Rs)",  U("Pmax","Vs","Rs") )
aF(1, 3, "Rlm=Rs", U("Rlm","Rs") )

sCat(1, 5, "Voltage and Current Source Equivalence", "") 
aF(1, 5, "Is=Vs/Rs", U("Is","Vs","Rs")) 
aF(1, 5, "Vs=Is*Rs", U("Vs","Is","Rs")) 


Cat(2, "Capacitors, E-Fields", "Compute electric field properties and capacitance of various types\nof structures")

CatVar(2, "A", "Area", "m2")
CatVar(2, "C", "Capacitance", "F")
CatVar(2, "cl", "Capacitance per unit length", "F/m")
CatVar(2, "d", "Separation", "m")
CatVar(2, "E", "Electric field", "V/m")
CatVar(2, "Er", "Radial electric field", "V/m")
CatVar(2, "Ez", "Electric field along z axis", "V/m")
CatVar(2, "F", "Force on plate", "N")
CatVar(2, "Q", "Charge", "C")
CatVar(2, "r", "Radial distance", "m")
CatVar(2, "ra", "Inner radius, wire radius", "m")
CatVar(2, "rb", "Outer radius", "m")
CatVar(2, "V", "Potential", "V")
CatVar(2, "Vz", "Potential along z axis", "V")
CatVar(2, "W", "Energy stored", "J")
CatVar(2, "z", "z axis distance from disk", "m")
CatVar(2, g.ep[2].."r", "Relative permittivity", "unitless")
CatVar(2, g.rh[2].."l", "Line charge", "C/m")
CatVar(2, g.rh[2].."s", "Charge density", "C/m2")

sCat(2, 1, "Point Charge", "")
aF(2, 1, "Er=Q/(4*"..g.pi[2].."*"..g.ep[2].."0*"..g.ep[2].."r*r^2)", U("Er","Q",g.ep[2].."0",g.ep[2].."r", "r") )
aF(2, 1, "V=Q/(4*"..g.pi[2].."*"..g.ep[2].."0*"..g.ep[2].."r*r)", U("V","Q",g.ep[2].."0",g.ep[2].."r", "r") )

sCat(2, 2, "Long Charged Line", "")
aF(2, 2, "Er="..g.rh[2].."l/(2*"..g.pi[2].."*"..g.ep[2].."0*"..g.ep[2].."r)", U("Er",g.rh[2].."l",g.ep[2].."0",g.ep[2].."r") )

sCat(2, 3, "Charged Disk", "")
aF(2, 3, "Ez=("..g.rh[2].."s/(2*"..g.ep[2].."0*"..g.ep[2].."r))*(1-abs(z)/sqrt(ra^2+z^2))", U("Ez",g.rh[2].."s",g.ep[2].."0",g.ep[2].."r","z","ra") )
aF(2, 3, "Vz=("..g.rh[2].."s/(2*"..g.ep[2].."0*"..g.ep[2].."r))*(sqrt(ra^2+z^2)-abs(z))", U("Vz",g.rh[2].."s",g.ep[2].."0",g.ep[2].."r","z","ra") )

sCat(2, 4, "Parallel Plates", "")
aF(2, 4, "E=V/d", U("E","V","d"))
aF(2, 4, "C=("..g.ep[2].."0*"..g.ep[2].."r*A)/d", U("C",g.ep[2].."0",g.ep[2].."r","A","d") )
aF(2, 4, "Q=C*V", U("Q","C","V"))
aF(2, 4, "F=-1/2*(V^2*C)/d", U("F","V","C","d") )
aF(2, 4, "W=1/2*V^2*C",U("W","V","C"))

sCat(2, 5, "Parallel Wires", "")
aF(2, 5, "cl="..g.pi[2].."*"..g.ep[2].."0*"..g.ep[2].."r/arccosh(d/(2*ra))", U("cl",g.ep[2].."0",g.ep[2].."r","d","ra") )

sCat(2, 6, "Coaxial Cable", "")
aF(2, 6, "V=("..g.rh[2].."l/(2*"..g.pi[2].."*"..g.ep[2].."0*"..g.ep[2].."r))*ln(rb/ra)", U("V",g.rh[2].."l",g.ep[2].."0",g.ep[2].."r","ra") )
aF(2, 6, "Er=V/(r*ln(rb/ra))", U("Er","V","r","rb","ra") )
aF(2, 6, "cl=(2*"..g.pi[2].."*"..g.ep[2].."0*"..g.ep[2].."r)/ln(rb/ra)", U("cl",g.ep[2].."0",g.ep[2].."r","rb","ra") )

sCat(2, 7, "Sphere", "")
aF(2, 7, "V=(Q/(4*"..g.pi[2].."*"..g.ep[2].."0*"..g.ep[2].."r))*(1/ra-1/rb)", U("V","Q",g.ep[2].."0",g.ep[2].."r","ra","rb") )
aF(2, 7, "Er=Q/(4*"..g.pi[2].."*"..g.ep[2].."0*"..g.ep[2].."r*r^2)", U("Er","Q","r",g.ep[2].."0",g.ep[2].."r") )
aF(2, 7, "C=(4*"..g.pi[2].."*"..g.ep[2].."0*"..g.ep[2].."r*ra*rb)/(rb-ra)", U("C",g.ep[2].."0",g.ep[2].."r","rb","ra") )


Cat(3, "Inductors and Magnetism", "Calculate electrical and magnetic properties of physical elements")

CatVar(3, g.th[2], "Angle", "rad")
CatVar(3, utf8(956).."r", "Relative permeability", "unitless")
CatVar(3, "a", "Loop radius or side of a rectangular loop", "m")
CatVar(3, "B", "Magnetic field", "T")
CatVar(3, "bl", "Width of rectangular loop", "m")
CatVar(3, "Bx", "Magnetic field, x axis", "T")
CatVar(3, "By", "Magnetic field, y axis", "T")
CatVar(3, "D", "Center-center wire spacing", "m")
CatVar(3, "d", "Strip width", "m")
CatVar(3, "f", "Frequency", "Hz")
CatVar(3, "Fw", "Force between wires/unit length", "N/m")
CatVar(3, "I", "Current", "A")
CatVar(3, "I1", "Current in line 1", "A")
CatVar(3, "I2", "Current in line 2", "A")
CatVar(3, "Is", "Current in strip", "A/m")
CatVar(3, "L", "Inductance per unit length", "H/m")
CatVar(3, "L12", "Mutual inductance", "H")
CatVar(3, "Ls", "Loop self-inductance", "H")
CatVar(3, "r", "Radial distance", "m")
CatVar(3, "ra", "Radius of inner conductor", "m")
CatVar(3, "rb", "Radius of outer conductor", "m")
CatVar(3, "Reff", "Effective resistance", g.omg[1]) --in Ohms
CatVar(3, "rr0", "Wire radius", "m")
CatVar(3, "T12", "Torque", "N*m")
CatVar(3, "x", "x axis distance", "m")
CatVar(3, "y", "y axis distance", "m")
CatVar(3, "z", "Distance to loop z axis", "m")
CatVar(3, g.de[2], "Skin depth", "m") --delta
CatVar(3, g.rh[2], "Resistivity", g.omg[1].."*m") --rho

sCat(3, 1, "Long Line", "")
aF(3, 1, "B=("..g.mu[2].."0*I)/(2*"..g.pi[2].."*r)", U("B",g.mu[2].."0","I","r",g.pi[2]) )

sCat(3, 2, "Long Strip", "")
aF(3, 2, "Bx=((-"..g.mu[2].."0*Is)/(2*"..g.pi[2].."))*(arctan((x+d/2)/y)-arctan((x-d/2)/y))", U("Bx",g.mu[2].."0","Is","x","d","y") )
aF(3, 2, "By=(("..g.mu[2].."0*Is)/(4*"..g.pi[2].."))*ln((y^2-(x+d/2)^2)/(y^2-(x-d/2)^2))", U("By",g.mu[2].."0","Is","x","d","y") )

sCat(3, 3, "Parallel Wires", "")
aF(3, 3, "Fw=("..g.mu[2].."0*I1*I2)/(2*"..g.pi[2].."*D)", U("Fw",g.mu[2].."0","I1","I2","D"))
aF(3, 3, "Bx=("..g.mu[2].."0/(2*"..g.pi[2].."))*(I1/x-I2/(D-x))", U("Bx",g.mu[2].."0","I1","I2","D","x" ))
aF(3, 3, "L=("..g.mu[2].."0/(4*"..g.pi[2].."))+("..g.mu[2].."0/("..g.pi[2].."))*arccosh(D/(2*a))", U("L",g.mu[2].."0","a","D" ))

sCat(3, 4, "Loop", "")
aF(3, 4, "B=("..g.mu[2].."0*I*a^2)/(2*(sqrt(a^2+z^2))^3)", U("B", g.mu[2].."0", "I", "a", "z") )
aF(3, 4, "Ls=("..g.mu[2].."0*a)*(ln(8*a/rr0)-2)", U(g.mu[2].."0", "a", "rr0") )
aF(3, 4, "L12=("..g.mu[2].."0*a)*cos("..g.th[2]..")/(2*"..g.pi[2]..")*ln((bl+d)/d)", U("L12", g.mu[2].."0", "a", g.th[2], g.pi[2], "bl", "d") )
aF(3, 4, "T12=("..g.mu[2].."0*a)*sin("..g.th[2]..")/(2*"..g.pi[2]..")*I1*I2*ln((bl+d)/d)", U("T12", g.mu[2].."0", "a", g.th[2], g.pi[2], "I1", "I2", "bl", "d") )

sCat(3, 5, "Coaxial Cable", "")
aF(3, 5, "L="..g.mu[2].."0/(8*"..g.pi[2]..")+"..g.mu[2].."0/(2*"..g.pi[2]..")*ln(rb/ra)", U("L", g.mu[2].."0", g.pi[2], "rb", "ra"))

sCat(3, 6, "Skin Effect", "")
aF(3, 6, g.de[2].."=1/(sqrt(("..g.pi[2].."*f*"..g.mu[2].."0*"..g.mu[2].."r)/"..g.rh[2].."))", U(g.de[2], g.mu[2].."0", g.mu[2].."r", g.pi[2], "f", g.rh[2]))
aF(3, 6, "Reff=sqrt(("..g.pi[2].."*f*"..g.mu[2].."0*"..g.mu[2].."r*"..g.rh[2].."))", U("Reff", g.mu[2].."0", g.mu[2].."r", g.pi[2], "f", g.rh[2]))


Cat(4, "Electron Motion", "Investigate the trajectories of electrons under the influence \nof electric and magnetic fields")

CatVar(4, "A0", "Richardson\'s constant", "A/(m2*K2)")
CatVar(4, "B", "Magnetic field", "T")
CatVar(4, "d", "Deflection tube diameter, plate spacing", "m")
CatVar(4, "f", "Frequency", "Hz")
CatVar(4, "f0", "Critical frequency", "Hz")
CatVar(4, "I", "Thermionic current", "A")
CatVar(4, "L", "Deflecting plate length", "m")
CatVar(4, "Ls", "Beam length to destination", "m")
CatVar(4, "r", "Radius of circular path", "m")
CatVar(4, "S", "Surface area", "m2")
CatVar(4, "T", "Temperature", "K")
CatVar(4, "v", "Vertical velocity", "m/s")
CatVar(4, "Va", "Accelerating voltage", "V")
CatVar(4, "Vd", "Deflecting voltage", "V")
CatVar(4, "y", "Vertical deflection", "m")
CatVar(4, "yd", "Beam deflection on screen", "m")
CatVar(4, "z", "Distance along beam axis", "m")
CatVar(4, g.ph[2], "Work function", "V")

sCat(4, 1, "Beam Deflection", "") 
aF(4, 1, "v=sqrt(2*(q/me)*Va)", U("v","q","me","Va")) 
aF(4, 1, "r=me*v/(q*B)", U("r","me","v","q","B")) 
aF(4, 1, "yd=L*Ls/(2*d*Va)*Vd", U("yd","L","Ls","d","Va","Vd")) 
aF(4, 1, "y=q*Vd/(2*me*d*v^2)*z^2", U("y","q","Vd","me","d","v","z")) 

sCat(4, 2, "Thermionic Emission", "") 
aF(4, 2, "I=A0*S*T^2*exp(-q*"..g.ph[2].."/(k*T))", U("I","A0","S","T","q",g.ph[2],"k")) 

sCat(4, 3, "Photoemission", "") 
aF(4, 3, "h*f=q*"..g.ph[2].."+1/2*me*v^2", U("h","f","q",g.ph[2],"me","v")) 
aF(4, 3, "f0=q*"..g.ph[2].."/h", U("f0","q",g.ph[2],"h")) 


Cat(5, "Meters and Bridge Circuits", "This category covers a variety of topics on meters, commonly used\nbridge and attenuator circuits")

CatVar(5, "a", "Resistance multiplier", "unitless")
CatVar(5, "b", "Resistance Multiplier", "unitless")
CatVar(5, "c", "Resistance Multiplier", "unitless")
CatVar(5, "CC3", "Capacitance, arm 3", "F")
CatVar(5, "CC4", "Capacitance, arm 4", "F")
CatVar(5, "Cs", "Series capacitor", "F")
CatVar(5, "Cx", "Unknown capacitor", "F")
CatVar(5, "DB", "Attenuator loss", "unitless")
CatVar(5, "f", "Frequency", "Hz")
CatVar(5, "Ig", "Galvanometer current", "A")
CatVar(5, "Imax", "Maximum current", "A")
CatVar(5, "Isen", "Current sensitivity", "A")
CatVar(5, "Lx", "Unknown inductance", "unitless")
CatVar(5, "Q", "Quality Factor", "unitless")
CatVar(5, "Radj", "Adjustable resistor", g.omg[1])
CatVar(5, "Rg", "Galvanometer resistance", g.omg[1])
CatVar(5, "Rj", "Resistance in L pad", g.omg[1])
CatVar(5, "Rk", "Resistance in L pad", g.omg[1])
CatVar(5, "Rl", "Resistance from left", g.omg[1])
CatVar(5, "Rm", "Meter resistance", g.omg[1])
CatVar(5, "Rr", "Resistance from right", g.omg[1])
CatVar(5, "RR1", "Resistance, arm 1", g.omg[1])
CatVar(5, "RR2", "Resistance, arm 2", g.omg[1])
CatVar(5, "RR3", "Resistance, arm 3", g.omg[1])
CatVar(5, "RR4", "Resistance, arm 4", g.omg[1])
CatVar(5, "Rs", "Series resistance", g.omg[1])
CatVar(5, "Rse", "Series resistance", g.omg[1])
CatVar(5, "Rsh", "Shunt resistance", "A")
CatVar(5, "Rx", "Unknown resistance", g.omg[1])
CatVar(5, "Vm", "Voltage across meter", "V")
CatVar(5, "Vmax", "Maximum voltage", "V")
CatVar(5, "Vs", "Source voltage", "V")
CatVar(5, "Vsen", "Voltage sensitivity", "V")
CatVar(5, g.omg[2], "Radian frequency", "rad/s")

sCat(5, 1, "A, V, Omega Meters", "") 
aF(5, 1, "Rsh=Rm*Isen/(Imax-Isen)", U("Rsh","Rm","Isen","Imax")) 
aF(5, 1, "Rs=(Vmax-Vsen)/Isen", U("Rs","Vmax","Vsen","Isen")) 
aF(5, 1, "Isen=Vs/(Rs+Rm+Radj/2)", U("Isen","Vs","Rs","Rm","Radj")) 

sCat(5, 2, "Wheatstone Bridge", "") 
aF(5, 2, "Rx/RR2=RR3/RR4", U("Rx","RR2","RR3","RR4")) 
aF(5, 2, "Vm=eegalv(Rx,RR2,RR3,RR4,Rg,Rs,Vs)", U("Vm","Rx","RR2","RR3","RR4","Rg","Rs","Vs")) 
aF(5, 2, "Ig=Vm/Rg", U("Ig","Vm","Rg")) 

sCat(5, 3, "Wien Bridge", "") 
aF(5, 3, "Cx=((RR3/RR1)-(Rs/Rx))*Cs", U("Cx","RR3","RR1","Rs","Rx","Cs")) 
aF(5, 3, "Cx=1/("..g.omg[2].."^2*Rs*Rx*Cs)", U("Cx",g.omg[2],"Rs","Rx","Cs")) 
aF(5, 3, "f=1/(2/"..g.pi[2].."*Cs*Rs)", U("f","Cs","Rs")) 
aF(5, 3, g.omg[2].."=2*"..g.pi[2].."*f", U(g.omg[2],"f")) 

sCat(5, 4, "Maxwell Bridge", "") 
aF(5, 4, "Cx=((RR3/RR1)-(Rs/Rx))*Cs", U("Cx","RR3","RR1","Rs","Rx","Cs")) 
aF(5, 4, "Cx=1/("..g.omg[2].."^2*Rs*Rx*Cs)", U("Cx",g.omg[2],"Rs","Rx","Cs")) 
aF(5, 4, "f=1/(2/"..g.pi[2].."*Cs*Rs)", U("f","Cs","Rs")) 
aF(5, 4, g.omg[2].."=2*"..g.pi[2].."*f", U(g.omg[2],"f")) 

sCat(5, 5, "Owen Bridge", "") 
aF(5, 5, "Lx=CC3*RR1*RR4", U("Lx","CC3","RR1","RR4")) 
aF(5, 5, "Rx=CC3*RR1/CC4-RR2", U("Rx","CC3","RR1","CC4","RR2")) 

sCat(5, 6, "Symmetrical Resistive Attenuator", "") 
aF(5, 6, "a=(10^(DB/20)-1)/(10^(DB/20)+1)", U("a","DB")) 
aF(5, 6, "b=2*10^(DB/20)/(10^(DB/10)-1)", U("b","DB")) 
aF(5, 6, "c=(10^(DB/20)-1)", U("c","DB")) 

sCat(5, 7, "Unsymmetrical Resistive Attenuator", "") 
aF(5, 7, "Rj=Rl-Rk*Rr/(Rk+Rr)", U("Rj","Rl","Rk","Rr")) 
aF(5, 7, "Rk=sqrt(Rl*Rr^2/(Rl-Rr))", U("Rk","Rl","Rr")) 
aF(5, 7, "DB=20*LOG(sqrt((Rl-Rr)/Rr)+sqrt(Rl/Rr))", U("DB","Rl","Rr")) 


Cat(6, "RL and RC Circuits", "Compute the natural and transient properties of simple RL\nand RC circuits")

CatVar(6, "C", "Capacitor", "F")
CatVar(6, "Cs", "Series capacitance", "F")
CatVar(6, "Cp", "Parallel capacitance", "F")
CatVar(6, "f", "Frequency", "Hz")
CatVar(6, "iC", "Capacitor current", "A")
CatVar(6, "iL", "Inductor current", "A")
CatVar(6, "I0", "Initial inductor current", "A")
CatVar(6, "L", "Inductance", "H")
CatVar(6, "Lp", "Parallel inductance", "H")
CatVar(6, "Ls", "Series inductance", "H")
CatVar(6, "Qp", "Q, parallel circuit", "unitless")
CatVar(6, "Qs", "Q, series circuit", "unitless")
CatVar(6, "R", "Resistance", g.omg[1])
CatVar(6, "Rp", "Parallel resistance", g.omg[1])
CatVar(6, "Rs", "Series resistance", g.omg[1])
CatVar(6, g.ta[2], "Time constant", "s")
CatVar(6, "t", "Time", "s")
CatVar(6, "vC", "Capacitor voltage", "V")
CatVar(6, "vL", "Inductor voltage", "V")
CatVar(6, "V0", "Initial capacitor voltage", "V")
CatVar(6, "Vs", "Voltage stimulus", "V")
CatVar(6, g.omg[2], "Radian frequency", "rad/s") --lowercase omega
CatVar(6, "W", "Energy dissipated", "J")

sCat(6, 1, "RL Natural Response", "") 
aF(6, 1, g.ta[2].."=L/R", U(g.ta[2],"L","R")) 
aF(6, 1, "vL=I0*R*exp(-t/"..g.ta[2]..")", U("vL","I0","R","t",g.ta[2])) 
aF(6, 1, "iL=I0*exp(-t/"..g.ta[2]..")", U("iL","I0","t",g.ta[2])) 
aF(6, 1, "W=1/2*L*I0^2*(1-exp(-2*t/"..g.ta[2].."))", U("W","L","I0","t",g.ta[2])) 

sCat(6, 2, "RC Natural Response", "") 
aF(6, 2, g.ta[2].."=R*C", U(g.ta[2],"R","C")) 
aF(6, 2, "vC=V0*exp(-t/"..g.ta[2]..")", U("vC","V0","t",g.ta[2])) 
aF(6, 2, "iC=V0/R*exp(-t/"..g.ta[2]..")", U("iC","V0","R","t",g.ta[2])) 
aF(6, 2, "W=1/2*C*V0^2*(1-exp(-2*t/"..g.ta[2].."))", U("W","C","V0","t",g.ta[2])) 

sCat(6, 3, "RL Step Response", "") 
aF(6, 3, g.ta[2].."=L/R", U(g.ta[2],"L","R")) 
aF(6, 3, "vL=(Vs-I0*R)*exp(-t/"..g.ta[2]..")", U("vL","Vs","I0","R","t",g.ta[2])) 
aF(6, 3, "iL=Vs/R+(I0-Vs/R)*exp(-t/"..g.ta[2]..")", U("iL","Vs","R","I0","t",g.ta[2])) 

sCat(6, 4, "RC Step Response", "") 
aF(6, 4, g.ta[2].."=R*C", U(g.ta[2],"R","C")) 
aF(6, 4, "vC=Vs+(V0-Vs)*exp(-t/"..g.ta[2]..")", U("vC","Vs","V0","t",g.ta[2])) 
aF(6, 4, "iC=(Vs-V0)/R*exp(-t/"..g.ta[2]..")", U("iC","Vs","V0","R","t",g.ta[2])) 

sCat(6, 5, "RL Series-Parallel", "") 
aF(6, 5, g.omg[2].."=2*"..g.pi[2].."*f", U(g.omg[2],"f")) 
aF(6, 5, "Qs="..g.omg[2].."*Ls/Rs", U("Qs",g.omg[2],"Ls","Rs")) 
aF(6, 5, "Rp=(Rs^2+"..g.omg[2].."^2*Ls^2)/Rs", U("Rp","Rs",g.omg[2],"Ls")) 
aF(6, 5, "Lp=(Rs^2+"..g.omg[2].."^2*Ls^2)/("..g.omg[2].."^2*Ls)", U("Lp","Rs",g.omg[2],"Ls")) 
aF(6, 5, "Qp=Rp/("..g.omg[2].."*Lp)", U("Qp","Rp",g.omg[2],"Lp")) 
aF(6, 5, "Rs="..g.omg[2].."^2*Lp^2*Rp/(Rp^2+"..g.omg[2].."^2*Lp^2)", U("Rs",g.omg[2],"Lp","Rp")) 
aF(6, 5, "Ls=Rp^2*Lp/(Rp^2+"..g.omg[2].."^2*Lp^2)", U("Ls","Rp","Lp",g.omg[2])) 
aF(6, 5, "Rp=Rs*(1+Qs^2)", U("Rp","Rs","Qs")) 
aF(6, 5, "Lp=Ls*(1+1/Qs^2)", U("Lp","Ls","Qs")) 
aF(6, 5, "Rs=Rp/(1+Qp^2)", U("Rs","Rp","Qp")) 
aF(6, 5, "Ls=Qp^2*Lp/(1+Qp^2)", U("Ls","Qp","Lp")) 

sCat(6, 6, "RC Series-Parallel", "") 
aF(6, 6, g.omg[2].."=2*"..g.pi[2].."*f", U(g.omg[2],"f")) 
aF(6, 6, "Qs=1/("..g.omg[2].."*Rs*Cs)", U("Qs",g.omg[2],"Rs","Cs")) 
aF(6, 6, "Rp=Rs*(1+1/("..g.omg[2].."^2*Rs^2*Cs^2))", U("Rp","Rs",g.omg[2],"Cs")) 
aF(6, 6, "Cp=Cs/(1+"..g.omg[2].."^2*Cs^2*Rs^2)", U("Cp","Cs",g.omg[2],"Rs")) 
aF(6, 6, "Qp="..g.omg[2].."*Rp*Cp", U("Qp",g.omg[2],"Rp","Cp")) 
aF(6, 6, "Rs=Rp/(1+"..g.omg[2].."^2*Rp^2*Cp^2)", U("Rs","Rp",g.omg[2],"Cp")) 
aF(6, 6, "Cs=(1+"..g.omg[2].."^2*Rp^2*Cp^2)/("..g.omg[2].."^2*Rp^2*Cp)", U("Cs",g.omg[2],"Rp","Cp")) 
aF(6, 6, "Rp=Rs*(1+Qs^2)", U("Rp","Rs","Qs")) 
aF(6, 6, "Cp=Cs/(1+1/Qs^2)", U("Cp","Cs","Qs")) 
aF(6, 6, "Rs=Rp/(1+Qp^2)", U("Rs","Rp","Qp")) 
aF(6, 6, "Cs=Cp*(1+Qp^2)/Qp^2", U("Cs","Cp","Qp")) 


Cat(7, "RLC Circuits", "Compute the impedance, admittance, natural response and\ntransient behavior of RLC circuits")

CatVar(7, g.al[2], "Neper\'s frequency", "rad/s") --alpha, apostrophe
CatVar(7, "A1", "Constant", "V")
CatVar(7, "A2", "Constant", "V")
CatVar(7, "B", "Susceptance", "S")
CatVar(7, "B1", "Constant", "V")
CatVar(7, "B2", "Constant", "V")
CatVar(7, "BC", "Capacitive susceptance", "S")
CatVar(7, "BL", "Inductive susceptance", "S")
CatVar(7, "C", "Capacitance", "F")
CatVar(7, "D1", "Constant", "V/s")
CatVar(7, "D2", "Constant", "V")
CatVar(7, "f", "Frequency", "Hz")
CatVar(7, "G", "Conductance", "S")
CatVar(7, "I0", "Initial inductor current", "A")
CatVar(7, "L", "Inductance", "H")
CatVar(7, g.th[2], "Phase angle", "rad")
CatVar(7, "R", "Resistance", g.omg[1])
CatVar(7, "s1", "Characteristic frequency", "rad/s")
CatVar(7, "s2", "Characteristic frequency", "rad/s")
CatVar(7, "s1i", "Characteristic frequency (imaginary)", "rad/s")
CatVar(7, "s1r", "Characteristic frequency (real)", "rad/s")
CatVar(7, "s2i", "Characteristic frequency (imaginary)", "rad/s")
CatVar(7, "s2r", "Characteristic frequency (real)", "rad/s")
CatVar(7, "t", "Time", "s")
CatVar(7, "v", "Capacitor voltage", "V")
CatVar(7, "V0", "Initial capacitor voltage", "V")
CatVar(7, g.omg[2], "Radian Frequency", "rad/s")
CatVar(7, g.omg[2].."d", "Damped radian frequency", "rad/s")
CatVar(7, g.omg[2].."0", "Classical radian frequency", "rad/s")
CatVar(7, "X", "Reactance", g.omg[1])
CatVar(7, "XXC", "Capacitive reactance", g.omg[1])
CatVar(7, "XL", "Inductive reactance", g.omg[1])
CatVar(7, "Ym", "Admittance "..utf8(8211).." magnitude", "S")
CatVar(7, "Zm", "Impedance "..utf8(8211).." magnitude", "S")

sCat(7, 1, "Series Impedance", "") 
aF(7, 1, "abs(Zm)^2=R^2+X^2", U("Zm","R","X")) 
aF(7, 1, g.th[2].."=arctan(X/R)", U(g.th[2],"X","R")) 
aF(7, 1, "X=XL+XXC", U("X","XL","XXC")) 
aF(7, 1, "XL="..g.omg[2].."*L", U("XL",g.omg[2],"L")) 
aF(7, 1, "XXC=-1/("..g.omg[2].."*C)", U("XXC",g.omg[2],"C")) 
aF(7, 1, g.omg[2].."=2*"..g.pi[2].."*f", U(g.omg[2],"f")) 

sCat(7, 2, "Parallel Admittance", "") 
aF(7, 2, "abs(Ym)^2=G^2+B^2", U("Ym","G","B")) 
aF(7, 2, g.th[2].."=arctan(G/B)", U(g.th[2],"G","B")) 
aF(7, 2, "G=1/R", U("G","R")) 
aF(7, 2, "B=BL+BC", U("B","BL","BC")) 
aF(7, 2, "BL=-1/("..g.omg[2].."*L)", U("BL",g.omg[2],"L")) 
aF(7, 2, "BC="..g.omg[2].."*C", U("BC",g.omg[2],"C")) 
aF(7, 2, g.omg[2].."=2*"..g.pi[2].."*f", U(g.omg[2],"f")) 

sCat(7, 3, "RLC Natural Response", "") 
aF(7, 3, "s1r=real(-"..g.al[2].."+sqrt("..g.al[2].."^2-"..g.omg[2].."0^2))", U("s1r",g.al[2],g.omg[2].."0")) 
aF(7, 3, "s1i=imag(-"..g.al[2].."+sqrt("..g.al[2].."^2-"..g.omg[2].."0^2))", U("s1i",g.al[2],g.omg[2].."0")) 
aF(7, 3, "s2r=real(-"..g.al[2].."-sqrt("..g.al[2].."^2-"..g.omg[2].."0^2))", U("s2r",g.al[2],g.omg[2].."0")) 
aF(7, 3, "s2i=imag(-"..g.al[2].."-sqrt("..g.al[2].."^2-"..g.omg[2].."0^2))", U("s2i",g.al[2],g.omg[2].."0")) 
aF(7, 3, g.omg[2].."0=sqrt(1/(L*C))", U(g.omg[2].."0","L","C")) 
aF(7, 3, g.al[2].."=1/(2*R*C)", U(g.al[2],"R","C")) 

sCat(7, 4, "Underdamped Transient Case", "") 
aF(7, 4, g.omg[2].."0=sqrt(1/(L*C))", U(g.omg[2].."0","L","C")) 
aF(7, 4, g.al[2].."=1/(2*R*C)", U(g.al[2],"R","C")) 
aF(7, 4, g.omg[2].."d=sqrt("..g.omg[2].."0^2-"..g.al[2].."^2)", U(g.omg[2].."d",g.omg[2].."0",g.al[2])) 
aF(7, 4, "v=B1*exp(-"..g.al[2].."*t)*cos("..g.omg[2].."d*t)+B2*exp(-"..g.al[2].."*t)*sin("..g.omg[2].."d*t)", U("v","B1",g.al[2],"t",g.omg[2].."d","B2")) 
aF(7, 4, "B1=V0", U("B1","V0")) 
aF(7, 4, "B2=-"..g.al[2].."/"..g.omg[2].."d*(V0-2R*I0)", U("B2",g.al[2],g.omg[2].."d","V0","R","I0")) 

sCat(7, 5, "Critically-Damped Transient Case", "") 
aF(7, 5, g.al[2].."=1/(2*R*C)", U(g.al[2],"R","C")) 
aF(7, 5, g.omg[2].."0=sqrt(1/(L*C))", U(g.omg[2].."0","L","C")) 
aF(7, 5, "v=D1*t*exp(-"..g.al[2].."*t)+D2*exp(-"..g.al[2].."*t)", U("v","D1","t",g.al[2],"D2")) 
aF(7, 5, "D1=I0/C+"..g.al[2].."*V0", U("D1","I0","C",g.al[2],"V0")) 
aF(7, 5, "D2=V0", U("D2","V0")) 

sCat(7, 6, "Overdamped Transient Case", "") 
aF(7, 6, "s1=-"..g.al[2].."+sqrt("..g.al[2].."^2-"..g.omg[2].."0^2)", U("s1",g.al[2],g.omg[2].."0")) 
aF(7, 6, "s2=-"..g.al[2].."-sqrt("..g.al[2].."^2-"..g.omg[2].."0^2)", U("s2",g.al[2],g.omg[2].."0")) 
aF(7, 6, g.omg[2].."0=1/sqrt(L*C)", U(g.omg[2].."0","L","C")) 
aF(7, 6, g.al[2].."=1/(2*R*C)", U(g.al[2],"R","C")) 
aF(7, 6, "v=A1*exp(s1*t)+A2*exp(s2*t)", U("v","A1","s1","t","A2","s2")) 
aF(7, 6, "A1=(V0*s2+1/C*(V0/R+I0))/(s2-s1)", U("A1","V0","s2","C","R","I0","s1")) 
aF(7, 6, "A2=-(V0*s1+1/C*(V0/R+I0))/(s2-s1)", U("A2","V0","s1","C","R","I0","s2")) 


Cat(8, "AC Circuits", "Calculate properties of AC circuits")

CatVar(8, "C", "Capacitance", "F")
CatVar(8, "f", "Frequency", "Hz")
CatVar(8, "I", "Instantaneous current", "A")
CatVar(8, "Im", "Current amplitude", "A")
CatVar(8, "L", "Inductance", "H")
CatVar(8, g.th[2], "Impedance phase angle", "rad")
CatVar(8, g.th[2].."1", "Phase angle 1", "rad")
CatVar(8, g.th[2].."2", "Phase angle 2", "rad")
CatVar(8, "R", "Resistance", g.omg[1])
CatVar(8, "RR1", "Resistance 1", g.omg[1])
CatVar(8, "RR2", "Resistance 2", g.omg[1])
CatVar(8, "t", "Time", "s")
CatVar(8, "V", "Total voltage", "V")
CatVar(8, "VC", "Voltage across capacitor", "V")
CatVar(8, "VL", "Voltage across inductor", "V")
CatVar(8, "Vm", "Maximum voltage", "V")
CatVar(8, "VR", "Voltage across resistor", "V")
CatVar(8, g.omg[2], "Radian frequency", "rad/s")
CatVar(8, "X", "Reactance", g.omg[1])
CatVar(8, "XX1", "Reactance 1", g.omg[1])
CatVar(8, "XX2", "Reactance 2", g.omg[1])
CatVar(8, "Yc", "Admittance", "S")
CatVar(8, "Z1m", "Impedance 1 magnitude", g.omg[1])
CatVar(8, "Z2m", "Impedance 2 magnitude", g.omg[1])
CatVar(8, "Zc", "Complex impedance", g.omg[1])
CatVar(8, "Zm", "Impedance magnitude", g.omg[1])

sCat(8, 1, "RL Series Impedance", "") 
aF(8, 1, "I=Im*sin("..g.omg[2].."*t)", U("I","Im",g.omg[2],"t")) 
aF(8, 1, "abs(Zm)^2=R^2+"..g.omg[2].."^2*L^2", U("Zm","R",g.omg[2],"L")) 
aF(8, 1, "VR=Zm*Im*sin("..g.omg[2].."*t)*cos("..g.th[2]..")", U("VR","Zm","Im",g.omg[2],"t",g.th[2])) 
aF(8, 1, "VL=Zm*Im*cos("..g.omg[2].."*t)*sin("..g.th[2]..")", U("VL","Zm","Im",g.omg[2],"t",g.th[2])) 
aF(8, 1, "V=VR+VL", U("V","VR","VL")) 
aF(8, 1, "Vm=Im*Zm", U("Vm","Im","Zm")) 
aF(8, 1, g.th[2].."=arctan("..g.omg[2].."*L/R)", U(g.th[2],g.omg[2],"L","R")) 
aF(8, 1, g.omg[2].."=2*"..g.pi[2].."*f", U(g.omg[2],"f")) 

sCat(8, 2, "RC Series Impedance", "") 
aF(8, 2, "I=Im*sin("..g.omg[2].."*t)", U("I","Im",g.omg[2],"t")) 
aF(8, 2, "abs(Zm)^2=R^2+1/("..g.omg[2].."*C)^2", U("Zm","R",g.omg[2],"C")) 
aF(8, 2, "VR=Zm*Im*sin("..g.omg[2].."*t)*cos("..g.th[2]..")", U("VR","Zm","Im",g.omg[2],"t",g.th[2])) 
aF(8, 2, "VC=Zm*Im*cos("..g.omg[2].."*t)*sin("..g.th[2]..")", U("VC","Zm","Im",g.omg[2],"t",g.th[2])) 
aF(8, 2, "V=VR+VC", U("V","VR","VC")) 
aF(8, 2, "Vm=Im*Zm", U("Vm","Im","Zm")) 
aF(8, 2, g.th[2].."=arctan(-1/("..g.omg[2].."*C*R))", U(g.th[2],g.omg[2],"C","R")) 
aF(8, 2, g.omg[2].."=2*"..g.pi[2].."*f", U(g.omg[2],"f")) 

sCat(8, 3, "Impedance <-> Admittance", "") 
aF(8, 3, "Yc=1/Zc", U("Yc", "Zc"))

sCat(8, 4, "Two Impedances in Series", "") 
aF(8, 4, "abs(Zm)^2=R^2+X^2", U("Zm","R","X")) 
aF(8, 4, g.th[2].."=arctan(X/R)", U(g.th[2],"X","R")) 
aF(8, 4, "R=RR1+RR2", U("R","RR1","RR2")) 
aF(8, 4, "X=XX1+XX2", U("X","XX1","XX2")) 
aF(8, 4, "abs(Z1m)^2=RR1^2+XX1^2", U("Z1m","RR1","XX1")) 
aF(8, 4, "abs(Z2m)^2=RR2^2+XX2^2", U("Z2m","RR2","XX2")) 
aF(8, 4, g.th[2].."1=arctan(XX1/RR1)", U(g.th[2].."1","XX1","RR1")) 
aF(8, 4, g.th[2].."2=arctan(XX2/RR2)", U(g.th[2].."2","XX2","RR2")) 

sCat(8, 5, "Two Impedances in Parallel", "") 
aF(8, 5, "abs(Zm)^2=((RR1*RR2-XX1*XX2)^2+(RR1*XX2+RR2*XX1)^2)/((RR1+RR2)^2+(XX1+XX2)^2)", U("Zm","RR1","RR2","XX1","XX2")) 
aF(8, 5, g.th[2].."=arctan((XX1*RR2+RR1*XX2)/(RR1*RR2-XX1*XX2))-arctan((XX1+XX2)/(RR1+RR2))", U(g.th[2],"XX1","RR2","RR1","XX2")) 
aF(8, 5, "R=Zm*cos("..g.th[2]..")", U("R","Zm",g.th[2])) 
aF(8, 5, "X=Zm*sin("..g.th[2]..")", U("X","Zm",g.th[2])) 
aF(8, 5, "abs(Z1m)^2=RR1^2+XX1^2", U("Z1m","RR1","XX1")) 
aF(8, 5, "abs(Z2m)^2=RR2^2+XX2^2", U("Z2m","RR2","XX2")) 
aF(8, 5, g.th[2].."1=arctan(XX1/RR1)", U(g.th[2].."1","XX1","RR1")) 
aF(8, 5, g.th[2].."2=arctan(XX2/RR2)", U(g.th[2].."2","XX2","RR2")) 


Cat(9, "Polyphase Circuits", "") 

CatVar(9, "IL", "Line current", "A")
CatVar(9, "Ip", "Phase current", "A")
CatVar(9, "P", "Power per phase", "W")
CatVar(9, "PT", "Total power", "W")
CatVar(9, g.th[2], "Impedance angle", "rad")
CatVar(9, "VL", "Line voltage", "V")
CatVar(9, "Vp", "Phase voltage", "V")
CatVar(9, "W1", "Wattmeter 1", "W")
CatVar(9, "W2", "Wattmeter 2", "W")

sCat(9, 1, "Balanced Delta Network", "") 
aF(9, 1, "VL=Vp", U("VL","Vp")) 
aF(9, 1, "IL=sqrt(3)*Ip", U("IL","Ip")) 
aF(9, 1, "P=Vp*Ip*cos("..g.th[2]..")", U("P","Vp","Ip",g.th[2])) 
aF(9, 1, "PT=3*Vp*Ip*cos("..g.th[2]..")", U("PT","Vp","Ip",g.th[2])) 
aF(9, 1, "PT=sqrt(3)*VL*IL*cos("..g.th[2]..")", U("PT","VL","IL",g.th[2])) 

sCat(9, 2, "Balanced Wye Network", "") 
aF(9, 2, "VL=sqrt(3)*Vp", U("VL","Vp")) 
aF(9, 2, "IL=Ip", U("IL","Ip")) 
aF(9, 2, "P=Vp*Ip*cos("..g.th[2]..")", U("P","Vp","Ip",g.th[2])) 
aF(9, 2, "PT=3*Vp*Ip*cos("..g.th[2]..")", U("PT","Vp","Ip",g.th[2])) 
aF(9, 2, "PT=sqrt(3)*VL*IL*cos("..g.th[2]..")", U("PT","VL","IL",g.th[2])) 

sCat(9, 3, "Power Measurements", "") 
aF(9, 3, "W1=VL*IL*cos("..g.th[2].."+"..g.pi[2].."/6)", U("W1","VL","IL",g.th[2],g.pi[2])) 
aF(9, 3, "W2=VL*IL*cos("..g.th[2].."-"..g.pi[2].."/6)", U("W2","VL","IL",g.th[2],g.pi[2])) 
aF(9, 3, "PT=sqrt(3)*VL*IL*cos("..g.th[2]..")", U("PT","VL","IL",g.th[2])) 


Cat(10, "Electrical Resonance", "") 

CatVar(10, g.al[2], "Damping coefficient", "rad/s")
CatVar(10, g.be[2], "Bandwidth", "rad/s")
CatVar(10, "C", "Capacitance", "F")
CatVar(10, "Im", "Current", "A")
CatVar(10, "L", "Inductance", "H")
CatVar(10, g.th[2], "Phase angle", "rad")
CatVar(10, "Q", "Quality factor", "unitless")
CatVar(10, "R", "Resistance", g.omg[1])
CatVar(10, "Rg", "Generator resistance", g.omg[1])
CatVar(10, "Vm", "Maximum voltage", "V")
CatVar(10, g.omg[2], "Radian frequency", "rad/s")
CatVar(10, g.omg[2].."0", "Resonant frequency", "rad/s")
CatVar(10, g.omg[2].."1", "Lower cutoff frequency", "rad/s")
CatVar(10, g.omg[2].."2", "Upper cutoff frequency", "rad/s")
CatVar(10, g.omg[2].."d", "Damped resonant frequency", "rad/s")
CatVar(10, g.omg[2].."m", "Frequency for maximum amplitude", "rad/s")
CatVar(10, "Yres", "Admittance at resonance", "S")
CatVar(10, "Z", "Impedance", g.omg[1])
CatVar(10, "Zres", "Impedance at resonance", g.omg[1])

sCat(10, 1, "Parallel Resonance I", "") 
aF(10, 1, "Vm=Im/sqrt(1/R^2+("..g.omg[2].."*C-1/("..g.omg[2].."*L))^2)", U("Vm","Im","R",g.omg[2],"C","L")) 
aF(10, 1, g.th[2].."=arctan(("..g.omg[2].."*C-1/("..g.omg[2].."*L))*R)", U(g.th[2],g.omg[2],"C","L","R")) 
aF(10, 1, g.omg[2].."0=1/sqrt(L*C)", U(g.omg[2].."0","L","C")) 
aF(10, 1, g.omg[2].."1=-1/(2*R*C)+sqrt(1/(2*R*C)^2+1/(L*C))", U(g.omg[2].."1","R","C","L")) 
aF(10, 1, g.omg[2].."2= 1/(2*R*C)+sqrt(1/(2*R*C)^2+1/(L*C))", U(g.omg[2].."2","R","C","L")) 
aF(10, 1, g.be[2].."="..g.omg[2].."2-"..g.omg[2].."1", U(g.be[2],g.omg[2].."2",g.omg[2].."1")) 
aF(10, 1, "Q="..g.omg[2].."0/"..g.be[2], U("Q",g.omg[2].."0",g.be[2])) 
aF(10, 1, "Q=R*sqrt(C/L)", U("Q","R","C","L")) 
aF(10, 1, "Q="..g.omg[2].."0*R*C", U("Q",g.omg[2].."0","R","C")) 

sCat(10, 2, "Parallel Resonance II", "") 
aF(10, 2, "Q="..g.omg[2].."0/"..g.be[2], U("Q",g.omg[2].."0",g.be[2])) 
aF(10, 2, g.omg[2].."1="..g.omg[2].."0*(-1/(2*Q)+sqrt(1/(2*Q)^2+1))", U(g.omg[2].."1",g.omg[2].."0","Q")) 
aF(10, 2, g.omg[2].."2="..g.omg[2].."0*( 1/(2*Q)+sqrt(1/(2*Q)^2+1))", U(g.omg[2].."2",g.omg[2].."0","Q")) 
aF(10, 2, g.al[2].."=1/(2*R*C)", U(g.al[2],"R","C")) 
aF(10, 2, g.al[2].."="..g.omg[2].."0/(2*Q)", U(g.al[2],g.omg[2].."0","Q")) 
aF(10, 2, g.omg[2].."d=sqrt("..g.omg[2].."0^2-"..g.al[2].."^2)", U(g.omg[2].."d",g.omg[2].."0",g.al[2])) 
aF(10, 2, g.omg[2].."d="..g.omg[2].."0*sqrt(1-1/(4*Q^2))", U(g.omg[2].."d",g.omg[2].."0","Q")) 

sCat(10, 3, "Resonance in a Lossy Inductor", "") 
aF(10, 3, g.omg[2].."0=sqrt(1/(L*C)-(R/L)^2)", U(g.omg[2].."0","L","C","R")) 
aF(10, 3, "Yres=(L+Rg*R*C)/(L*Rg)", U("Yres","L","Rg","R","C")) 
aF(10, 3, "Zres=1/Yres", U("Zres","Yres")) 
aF(10, 3, g.omg[2].."m=sqrt(sqrt((1/(L*C))^2*(1+2*R/Rg)+(R/L)^2*(2/(L*C)))-(R/L)^2)", U(g.omg[2].."m","L","C","R","Rg")) 

sCat(10, 4, "Series Resonance", "") 
aF(10, 4, g.omg[2].."0=(1/sqrt(L*C))", U(g.omg[2].."0","L","C")) 
aF(10, 4, "Z=sqrt(R^2+("..g.omg[2].."*L-1/("..g.omg[2].."*C))^2)", U("Z","R",g.omg[2],"L","C")) 
aF(10, 4, g.th[2].."=arctan(("..g.omg[2].."*L-1/("..g.omg[2].."*C))/R)", U(g.th[2],g.omg[2],"L","C","R")) 
aF(10, 4, g.omg[2].."1=-R/(2*L)+sqrt((R/(2*L))^2+1/(L*C))", U(g.omg[2].."1","R","L","C")) 
aF(10, 4, g.omg[2].."2=R/(2*L)+sqrt((R/(2*L))^2+1/(L*C))", U(g.omg[2].."2","R","L","C")) 
aF(10, 4, g.be[2].."="..g.omg[2].."2-"..g.omg[2].."1", U(g.be[2],g.omg[2].."2",g.omg[2].."1")) 
aF(10, 4, g.be[2].."=R/L", U(g.be[2],"R","L")) 
aF(10, 4, "Q="..g.omg[2].."0*L/R", U("Q",g.omg[2].."0","L","R")) 
aF(10, 4, "Q=1/R*sqrt(L/C)", U("Q","R","L","C")) 


Cat(11, "OpAmp Circuits", "") 

CatVar(11, "Acc", "Common Mode current gain", "unitless", "")
CatVar(11, "Aco", "Common Mode gain from real OpAmp", "unitless")
CatVar(11, "Ad", "Differential mode gain", "unitless")
CatVar(11, "Agc", "Transconductance", "S")
CatVar(11, "Aic", "Current gain", "unitless")
CatVar(11, "Av", "Voltage gain", "unitless")
CatVar(11, "CC1", "Input capacitor", "F")
CatVar(11, "Cf", "Feedback capacitor", "F")
CatVar(11, "CMRR", "CM rejection ratio", "unitless")
CatVar(11, "Cp", "Bypass capacitor", "F")
CatVar(11, "fcp", "3dB bandwidth, circuit", "Hz")
CatVar(11, "fd", "Characteristic frequency", "Hz")
CatVar(11, "f0", "Passband, geometric center", "Hz")
CatVar(11, "fop", "3dB bandwidth, OpAmp", "Hz")
CatVar(11, "IIf", "Maximum current through Rf", "A")
CatVar(11, "RR1", "Input resistor", g.omg[1])
CatVar(11, "RR2", "Current stabilizor", g.omg[1])
CatVar(11, "RR3", "Feedback resistor", g.omg[1])
CatVar(11, "RR4", "Resistor", g.omg[1])
CatVar(11, "Rf", "Feedback resistor", g.omg[1])
CatVar(11, "Rin", "Input resistance", g.omg[1])
CatVar(11, "Rl", "Load resistance", g.omg[1])
CatVar(11, "Ro", "Output resistance, OpAmp", g.omg[1])
CatVar(11, "Rout", "Output resistance", g.omg[1])
CatVar(11, "Rp", "Bias current resistor", g.omg[1])
CatVar(11, "Rs", "Voltage divide resistor", g.omg[1])
CatVar(11, "tr", "10-90% rise time", "s")
CatVar(11, "dVH", "Hysteresis", "V")
CatVar(11, "VL", "Detection threshold, low", "V")
CatVar(11, "Vomax", "Maximum circuit output", "V")
CatVar(11, "VR", "Reference voltage", "V")
CatVar(11, "Vrate", "Maximum voltage rate", "V/s")
CatVar(11, "VU", "Detection threshold, high", "V")
CatVar(11, "Vz1", "Zener breakdown 1", "V")
CatVar(11, "Vz2", "Zener breakdown 2", "V")

sCat(11, 1, "Basic Inverter", "") 
aF(11, 1, "Av=-Rf/RR1", U("Av","Rf","RR1")) 
aF(11, 1, "Rp=RR1*Rf/(RR1+Rf)", U("Rp","RR1","Rf")) 
aF(11, 1, "fcp=fop*Av*(RR1/Rf)", U("fcp","fop","Av","RR1","Rf")) 
aF(11, 1, "tr=0.35*Rf/(fop*Av*RR1)", U("tr","Rf","fop","Av","RR1")) 

sCat(11, 2, "Non-Inverting Amplifier", "") 
aF(11, 2, "Av=1+Rf/RR1", U("Av","Rf","RR1")) 
aF(11, 2, "Rp=RR1*Rf/(RR1+Rf)", U("Rp","RR1","Rf")) 

sCat(11, 3, "Current Amplifier", "") 
aF(11, 3, "Aic=(Rs+Rf)*Av/(Rl+Ro+Rs*(1+Av))", U("Aic","Rs","Rf","Av","Rl","Ro")) 
aF(11, 3, "Rin=Rf/(1+Av)", U("Rin","Rf","Av")) 
aF(11, 3, "Rout=Rs*(1+Av)", U("Rout","Rs","Av")) 

sCat(11, 4, "Transconductance Amplifier", "") 
aF(11, 4, "Agc=1/Rs", U("Agc","Rs")) 
aF(11, 4, "Rout=Rs*(1+Av)", U("Rout","Rs","Av")) 

sCat(11, 5, "Level Detector (Inverting)", "") 
aF(11, 5, "RR1=Rp*Rf/(Rp+Rf)", U("RR1","Rp","Rf")) 
aF(11, 5, "dVH=(Vz1+Vz2)*Rp/(Rp+Rf)", U("dVH","Vz1","Vz2","Rp","Rf")) 
aF(11, 5, "VU=(VR*Rf+Rp*Vz1)/(Rf+Rp)", U("VU","VR","Rf","Rp","Vz1")) 
aF(11, 5, "VL=(VR*Rf-Rp*Vz2)/(Rf+Rp)", U("VL","VR","Rf","Rp","Vz2")) 

sCat(11, 6, "Level Detector (Non-inverting)", "") 
aF(11, 6, "RR1=Rp*Rf/(Rp+Rf)", U("RR1","Rp","Rf")) 
aF(11, 6, "dVH=(Vz1+Vz2)*Rp/(Rp+Rf)", U("dVH","Vz1","Vz2","Rp","Rf")) 
aF(11, 6, "VU=(VR*(Rf+Rp)+Rp*Vz2)/Rf", U("VU","VR","Rf","Rp","Vz2")) 
aF(11, 6, "VL=(VR*(Rp+Rf)-Rp*Vz1)/Rf", U("VL","VR","Rp","Rf","Vz1")) 

sCat(11, 7, "Differentiator", "") 
aF(11, 7, "Rf=Vomax/IIf", U("Rf","Vomax","IIf")) 
aF(11, 7, "Rp=Rf", U("Rp","Rf")) 
aF(11, 7, "CC1=Vomax/(Rf*Vrate)", U("CC1","Vomax","Rf","Vrate")) 
aF(11, 7, "RR1=1/(2*"..g.pi[2].."*fd*CC1)", U("RR1","fd","CC1")) 
aF(11, 7, "fd=1/(2*"..g.pi[2].."*Rf*CC1)", U("fd","Rf","CC1")) 
aF(11, 7, "Cp=10/(2*"..g.pi[2].."*f0*Rp)", U("Cp","f0","Rp")) 
aF(11, 7, "Cf=1/(4*"..g.pi[2].."*f0*Rf)", U("Cf","f0","Rf")) 

sCat(11, 8, "Differential Amplifier", "") 
aF(11, 8, "Ad=RR3/RR1", U("Ad","RR3","RR1")) 
aF(11, 8, "Aco=RR3^2/(RR1*(RR1+RR3)*CMRR)", U("Aco","RR3","RR1","CMRR")) 
aF(11, 8, "Ad=(Av*RR3)/sqrt(RR1^2*Av^2+RR3^2)", U("Ad","Av","RR3","RR1")) 
aF(11, 8, "Acc=(RR4*RR1-RR2*RR3)/(RR1*(RR2+RR4))", U("Acc","RR4","RR1","RR2","RR3")) 


Cat(12, "Solid State Devices", "") 

CatVar(12, g.al[2], "CB current gain", "unitless")
CatVar(12, "aLGJ", "Linearly graded junction parameter", "1/m4")
CatVar(12, "A", "Area", "m2")
CatVar(12, "A1", "EB junction area", "m2")
CatVar(12, "A2", "CB junction area", "m2")
CatVar(12, g.al[2].."f", "Forward "..g.al[2], "unitless")
CatVar(12, "Aj", "Junction area", "m2")
CatVar(12, g.al[2].."r", "Reverse "..g.al[2], "unitless")
CatVar(12, g.be[2], "CE current gain", "unitless")
CatVar(12, "b", "Channel width", "m")
CatVar(12, g.be[2].."f", "Forward "..g.be[2], "unitless")
CatVar(12, g.be[2].."r", "Reverse "..g.be[2], "unitless")
CatVar(12, "Cj", "Junction capacitance", "F")
CatVar(12, "CL", "Load capacitance", "F")
CatVar(12, "Cox", "Oxide capacitance per unit area", "F/m2")
CatVar(12, "D", "Diffusion coefficient", "m2/s")
CatVar(12, "DB", "Base diffusion coefficient", "m2/s")
CatVar(12, "DC", "Collector diffusion coefficient", "m2/s")
CatVar(12, "DE", "Emitter diffusion coefficient", "m2/s")
CatVar(12, "Dn", "n diffusion coefficient", "m2/s")
CatVar(12, "Dp", "p diffusion coefficient", "m2/s")
CatVar(12, g.ep[2].."ox", "Oxide permittivity", "unitless")
CatVar(12, g.ep[2].."s", "Silicon Permittivity", "unitless")
CatVar(12, "Ec", "Conduction band", "J")
CatVar(12, "EF", "Fermi level", "J")
CatVar(12, "Ei", "Intrinsic Fermi level", "J")
CatVar(12, "Ev", "Valence band", "J")
CatVar(12, "ffmax", "Maximum frequency", "Hz")
CatVar(12, utf8(947), "Body coefficient", "V5")
CatVar(12, "gd", "Drain conductance", "S")
CatVar(12, "gm", "Transconductance", "S")
CatVar(12, "gmL", "Transconductance, load device", "S")
CatVar(12, "Go", "Conductance", "S")
CatVar(12, "I", "Junction current", "A")
CatVar(12, "I0", "Saturation current", "A")
CatVar(12, "IB", "Base current", "A")
CatVar(12, "IC", "Collector current", "A")
CatVar(12, "ICB0", "CB leakage, E open", "A")
CatVar(12, "ICE0", "CE leakage, B open", "A")
CatVar(12, "ICsat", "Collector I at saturation edge", "A")
CatVar(12, "ID", "Drain current", "A")
CatVar(12, "IDmod", "Channel modulation drain current", "A")
CatVar(12, "ID0", "Drain current at zero bias", "A")
CatVar(12, "IDsat", "Drain saturation current", "A")
CatVar(12, "IE", "Emitter current", "A")
CatVar(12, "IIf", "Forward current", "A")
CatVar(12, "Ir", "Reverse current", "A")
CatVar(12, "Ir0", "E-M reverse current component", "A")
CatVar(12, "IRG", "G-R current", "A")
CatVar(12, "IRG0", "Zero bias G-R current", "A")
CatVar(12, "Is", "Saturation current", "A")
CatVar(12, utf8(955), "Modulation parameter", "1/V")
CatVar(12, "Is", "Saturation current", "A")
CatVar(12, "kD", "MOS constant, driver", "A/V2")
CatVar(12, "kL", "MOS constant, load", "A/V2")
CatVar(12, "kn", "MOS constant", "A/V2")
CatVar(12, "kn1", "MOS process constant", "A/V2")
CatVar(12, "kN", "MOS constant, n channel", "A/V2")
CatVar(12, "kP", "MOS constant, p channel", "A/V2")
CatVar(12, "KR", "Ratio", "unitless")
CatVar(12, "L", "Transistor length", "m")
CatVar(12, "LC", "Diffusion length, collector", "m")
CatVar(12, "LD", "Drive transistor length", "m")
CatVar(12, "LE", "Diffusion length, emitter", "m")
CatVar(12, "LL", "Load transistor length", "m")
CatVar(12, "LLn", "Diffusion length, n", "m")
CatVar(12, "lNN", "n-channel length", "m")
CatVar(12, "Lp", "Diffusion length, p", "m")
CatVar(12, "lP", "p-channel length", "m")
CatVar(12, g.mu[2].."n", "n (electron) mobility", "m2/(V*s)")
CatVar(12, g.mu[2].."p", "p (positive charge) mobility", "m2/(V*s)")
CatVar(12, "mn", "n effective mass", "unitless")
CatVar(12, "mp", "p effective mass", "unitless")
CatVar(12, "N", "Doping concentration", "1/m3")
CatVar(12, "Na", "Acceptor density", "1/m3")
CatVar(12, "nC", "n density, collector", "1/m3")
CatVar(12, "Nd", "Donor density", "1/m3")
CatVar(12, "nE", "n density, emitter", "1/m3")
CatVar(12, "ni", "Intrinsic density", "1/m3")
CatVar(12, "N0", "Surface concentration", "1/m3")
CatVar(12, "npo", "n density in p material", "1/m3")
CatVar(12, "p", "p density", "1/m3")
CatVar(12, "pB", "p density, base", "1/m3")
CatVar(12, g.ph[2].."F", "Fermi potential", "V")
CatVar(12, g.ph[2].."GC", "Work function potential", "V")
CatVar(12, "pno", "p density in n material", "1/m3")
CatVar(12, "Qtot", "Total surface impurities", "unitless")
CatVar(12, "Qb", "Bulk charge at bias", "C/m2")
CatVar(12, "Qb0", "Bulk charge at 0 bias", "C/m2")
CatVar(12, "Qox", "Oxide charge density", "C/m2")
CatVar(12, "Qsat", "Base Q, transition edge", "C")
CatVar(12, g.rh[2].."n", "n resistivity", g.omg[1].."*m")
CatVar(12, g.rh[2].."p", "p resistivity", g.omg[1].."*m")
CatVar(12, "Rl", "Load resistance", g.omg[1])
CatVar(12, g.ta[2].."B", "lifetime in base", "s")
CatVar(12, g.ta[2].."D", "Time constant", "s")
CatVar(12, g.ta[2].."L", "Time constant", "s")
CatVar(12, g.ta[2].."o", "Lifetime", "s")
CatVar(12, g.ta[2].."p", "Minority carrier lifetime", "s")
CatVar(12, g.ta[2].."t", "Base transit time", "s")
CatVar(12, "t", "Time", "s")
CatVar(12, "TT", "Temperature", "K")
CatVar(12, "tch", "Charging time", "s")
CatVar(12, "tdis", "Discharge time", "s")
CatVar(12, "tox", "Gate oxide thickness", "m")
CatVar(12, "tr", "Collector current rise time", "s")
CatVar(12, "ts", "Charge storage time", "s")
CatVar(12, "tsd1", "Storage delay, turn off", "s")
CatVar(12, "tsd2", "Storage delay, turn off", "s")
CatVar(12, "Ttr", "Transit time", "s")
CatVar(12, "V1", "Input voltage", "V")
CatVar(12, "Va", "Applied voltage", "V")
CatVar(12, "Vbi", "Built-in voltage", "V")
CatVar(12, "VBE", "BE bias voltage", "V")
CatVar(12, "VCB", "CB bias voltage", "V")
CatVar(12, "VCC", "Collector supply voltage", "V")
CatVar(12, "VCEs", "CE saturation voltage", "V")
CatVar(12, "VDD", "Drain supply voltage", "V")
CatVar(12, "VDS", "Drain voltage", "V")
CatVar(12, "VDsat", "Drain saturation voltage", "V")
CatVar(12, "VEB", "EB bias voltage", "V")
CatVar(12, "VG", "Gate voltage", "V")
CatVar(12, "VGS", "Gate to source voltage", "V")
CatVar(12, "VIH", "Input high", "V")
CatVar(12, "Vin", "Input voltage", "V")
CatVar(12, "VIL", "Input low voltage", "V")
CatVar(12, "VL", "Load voltage", "V")
CatVar(12, "VM", "Midpoint voltage", "V")
CatVar(12, "VOH", "Output high", "V")
CatVar(12, "VOL", "Output low", "V")
CatVar(12, "Vo", "Output voltage", "V")
CatVar(12, "Vp", "Pinchoff voltage", "V")
CatVar(12, "VSB", "Substrate bias", "V")
CatVar(12, "VT", "Threshold voltage", "V")
CatVar(12, "VT0", "Threshold voltage at 0 bias", "V")
CatVar(12, "VTD", "Depletion transistor threshold", "V")
CatVar(12, "VTL", "Load transistor threshold", "V")
CatVar(12, "VTL0", "Load transistor threshold", "V")
CatVar(12, "VTN", "n channel threshold", "V")
CatVar(12, "VTP", "p channel threshold", "V")
CatVar(12, "W", "MOS transistor width", "m")
CatVar(12, "WB", "Base width", "m")
CatVar(12, "WD", "Drive transistor width", "m")
CatVar(12, "WL", "Load transistor width", "m")
CatVar(12, "WN", "n-channel width", "m")
CatVar(12, "WP", "p-channel width", "m")
CatVar(12, "x", "Depth from surface", "m")
CatVar(12, "xd", "Depletion layer width", "m")
CatVar(12, "xn", "Depletion width, n side", "m")
CatVar(12, "xp", "Depletion width, p side", "m")
CatVar(12, "Z", "JFET width", "m")

sCat(12, 1, "Semiconductor Basics", "") 
aF(12, 1, g.rh[2].."n=1/(q*"..g.mu[2].."n*Nd)", U(g.rh[2].."n","q",g.mu[2].."n","Nd")) 
aF(12, 1, g.rh[2].."p=1/(q*"..g.mu[2].."p*Na)", U(g.rh[2].."p","q",g.mu[2].."p","Na")) 
aF(12, 1, "Dn=((k*TT)/q)*"..g.mu[2].."n", U("Dn","k","TT","q",g.mu[2].."n")) 
aF(12, 1, "Dp=((k*TT)/q)*"..g.mu[2].."p", U("Dp","k","TT","q",g.mu[2].."p")) 
aF(12, 1, "Ei=EF+(k*TT*ln(Na/ni(TT)))", U("Ei","EF","k","TT","Na")) 
aF(12, 1, "EF=Ei+(k*TT*ln(Nd/ni(TT)))", U("EF","Ei","k","TT","Nd")) 
aF(12, 1, "Ei=(Ec+Ev)/2+3/4*(k*TT)*ln(mp/mn)", U("Ei","Ec","Ev","k","TT","mp","mn")) 
aF(12, 1, "N/N0=erfc(x/(2*sqrt(D*t)))", U("N","N0","x","D","t")) 
aF(12, 1, "N=Qtot/(A*sqrt("..g.pi[2].."*D*t))*exp(-x^2/(4*D*t))", U("N","Qtot","A","D","t","x")) 

sCat(12, 2, "PN Junctions", "") 
aF(12, 2, "Vbi=k*TT/q*ln(Nd*Na/ni(TT)^2)", U("Vbi","k","TT","q","Nd","Na")) 
aF(12, 2, "xn=sqrt(2*"..g.ep[2].."s*"..g.ep[2].."0*abs(Vbi-Va)*Na/(q*Nd*(Na+Nd)))", U("xn",g.ep[2].."s",g.ep[2].."0","Vbi","Va","Na","q","Nd")) 
aF(12, 2, "xp=(Nd/Na)*xn", U("xp","Nd","Na","xn")) 
aF(12, 2, "xd=xn+xp", U("xd","xn","xp")) 
aF(12, 2, "Cj="..g.ep[2].."s*"..g.ep[2].."0*Aj/xd", U("Cj",g.ep[2].."s",g.ep[2].."0","Aj","xd")) 
aF(12, 2, "Vbi=2*k*TT/q*ln(aLGJ*xd/(2*ni(TT)))", U("Vbi","k","TT","q","aLGJ","xd")) 
aF(12, 2, "xd=(12*"..g.ep[2].."s*"..g.ep[2].."0/(q*aLGJ)*abs(Vbi-Va))^(1/3)", U("xd",g.ep[2].."s",g.ep[2].."0","q","aLGJ","Vbi","Va")) 

sCat(12, 3, "PN Junction Currents", "") 
aF(12, 3, "I=q*Aj*(Dn/LLn*npo+Dp/Lp*pno)*(exp(q*Va/(k*TT))-1)", U("I","q","Aj","Dn","LLn","npo","Dp","Lp","pno","Va","k","TT")) 
aF(12, 3, "I=I0*(exp(q*Va/(k*TT))-1)", U("I","I0","q","Va","k","TT")) 
aF(12, 3, "I0=q*Aj*(Dn/LLn*npo+Dp/Lp*pno)", U("I0","q","Aj","Dn","LLn","npo","Dp","Lp","pno")) 
aF(12, 3, "IRG0=-q*Aj*ni(TT)*xd/(2*"..g.ta[2].."o)", U("IRG0","q","Aj","TT","xd",g.ta[2].."o")) 
aF(12, 3, "IRG=q*Aj*ni(TT)*xd/(2*"..g.ta[2].."o)*(exp(q*Va/(2*k*TT))-1)", U("IRG","q","Aj","TT","xd",g.ta[2].."o","Va","k")) 
aF(12, 3, "Go=q/(k*TT)*(I+I0)", U("Go","q","k","TT","I","I0")) 
aF(12, 3, "ts="..g.ta[2].."p*ln(1+IIf/Ir)", U("ts",g.ta[2].."p","IIf","Ir")) 
aF(12, 3, "1/(1+Ir/IIf)=erf(sqrt(ts/"..g.ta[2].."p))", U("Ir","IIf","ts",g.ta[2].."p")) 

sCat(12, 4, "Transistor Currents", "") 
aF(12, 4, g.al[2].."=IC/IE", U(g.al[2],"IC","IE")) 
aF(12, 4, g.be[2].."="..g.al[2].."/(1-"..g.al[2]..")", U(g.be[2],g.al[2])) 
aF(12, 4, "IE=IB+IC", U("IE","IB","IC")) 
aF(12, 4, "IC="..g.al[2].."*IE+ICB0", U("IC",g.al[2],"IE","ICB0")) 
aF(12, 4, "IC="..g.al[2].."/(1-"..g.al[2]..")*IB+ICB0/(1-"..g.al[2]..")", U("IC",g.al[2],"IB","ICB0")) 
aF(12, 4, "IC="..g.be[2].."*IB+ICE0", U("IC",g.be[2],"IB","ICE0")) 
aF(12, 4, "ICE0=ICB0*("..g.be[2].."+1)", U("ICE0","ICB0",g.be[2])) 

sCat(12, 5, "Ebers-Moll Equations", "") 
aF(12, 5, "IE=IIf-"..g.al[2].."r*Ir", U("IE","IIf",g.al[2].."r","Ir")) 
aF(12, 5, "IC="..g.al[2].."f*IIf-Ir", U("IC",g.al[2].."f","IIf","Ir")) 
aF(12, 5, "IB=(1-"..g.al[2].."f)*IIf+(1-"..g.al[2].."r)*Ir", U("IB",g.al[2].."f","IIf",g.al[2].."r","Ir")) 
aF(12, 5, g.be[2].."f="..g.al[2].."f/(1-"..g.al[2].."f)", U(g.be[2].."f",g.al[2].."f")) 
aF(12, 5, g.be[2].."r="..g.al[2].."r/(1-"..g.al[2].."r)", U(g.be[2].."r",g.al[2].."r")) 
aF(12, 5, g.al[2].."f*IIf=Is", U(g.al[2].."f","IIf","Is")) 
aF(12, 5, g.al[2].."r*Ir=Is", U(g.al[2].."r","Ir","Is")) 
aF(12, 5, "ICB0=(1-"..g.al[2].."r*"..g.al[2].."f)*Ir0", U("ICB0",g.al[2].."r",g.al[2].."f","Ir0")) 
aF(12, 5, "ICE0=ICB0*("..g.be[2].."f+1)", U("ICE0","ICB0",g.be[2].."f")) 
aF(12, 5, "ICE0=Ir0*(1-"..g.al[2].."f*"..g.al[2].."r)/(1-"..g.al[2].."f)", U("ICE0","Ir0",g.al[2].."f",g.al[2].."r")) 

sCat(12, 6, "Ideal Currents - pnp", "") 
aF(12, 6, "IE=q*A1*(DE*nE/LE+DB*pB/WB)*(exp((q*VEB)/(k*TT))-1)-q*A2*DB/WB*pB*(exp((q*VCB)/(k*TT))-1)", U("IE","q","A1","DE","nE","LE","DB","pB","WB","VEB","k","TT","A2","VCB")) 
aF(12, 6, "IC=q*A1*DB*pB/WB*(exp((q*VEB)/(k*TT))-1)-q*A2*(DC*nC/LC+DB*pB/WB)*(exp((q*VCB)/(k*TT))-1)", U("IC","q","A1","DB","pB","WB","VEB","k","TT","A2","DC","nC","LC","VCB")) 
aF(12, 6, "IB=q*A1*DE/LE*nE*(exp((q*VBE)/(k*TT))-1)+q*A2*DC/LC*nC*(exp((q*VCB)/(k*TT))-1)", U("IB","q","A1","DE","LE","nE","VBE","k","TT","A2","DC","LC","nC","VCB")) 
aF(12, 6, g.al[2].."=((DB*pB)/WB)/(DB*pB/WB+DE*nE/LE)", U(g.al[2],"DB","pB","WB","DE","nE","LE")) 

sCat(12, 7, "Switching Transients", "") 
aF(12, 7, "Qsat=ICsat*"..g.ta[2].."t", U("Qsat","ICsat",g.ta[2].."t")) 
aF(12, 7, "ICsat=VCC/Rl", U("ICsat","VCC","Rl")) 
aF(12, 7, "tr="..g.ta[2].."B*ln(1/(1-(ICsat*"..g.ta[2].."t)/(IB*"..g.ta[2].."B)))", U("tr",g.ta[2].."B","ICsat",g.ta[2].."t","IB")) 
aF(12, 7, "tsd1="..g.ta[2].."B*ln(IB*"..g.ta[2].."B/(ICsat*"..g.ta[2].."t))", U("tsd1",g.ta[2].."B","IB","ICsat",g.ta[2].."t")) 
aF(12, 7, "tsd2="..g.ta[2].."B*ln(2*IB*"..g.ta[2].."B/(ICsat*"..g.ta[2].."t*(1+IB*"..g.ta[2].."B/(ICsat*"..g.ta[2].."t))))", U("tsd2",g.ta[2].."B","IB","ICsat",g.ta[2].."t")) 
aF(12, 7, "VCEs=k*TT/q*ln(1+IC/IB*(1-"..g.al[2].."r)/("..g.al[2].."r*(1-IC/IB*(1-"..g.al[2].."f)/"..g.al[2].."f)))", U("VCEs","k","TT","q","IC","IB",g.al[2].."r",g.al[2].."f")) 

sCat(12, 8, "MOS Transistor I", "") 
aF(12, 8, g.ph[2].."F=k*TT/q*ln(ni(TT)/p)", U(g.ph[2].."F","k","TT","q","p")) 
aF(12, 8, "xd=sqrt(2*"..g.ep[2].."s*"..g.ep[2].."0*(2*"..g.ph[2].."F)/(q*Na))", U("xd",g.ep[2].."s",g.ep[2].."0",g.ph[2].."F","q","Na")) 
aF(12, 8, "Qb0=-sqrt(2*q*Na*"..g.ep[2].."s*"..g.ep[2].."0*abs(2*"..g.ph[2].."F))", U("Qb0","q","Na",g.ep[2].."s",g.ep[2].."0",g.ph[2].."F")) 
aF(12, 8, "Qb=-sqrt(2*q*Na*"..g.ep[2].."s*"..g.ep[2].."0*abs(-2*"..g.ph[2].."F+VSB))", U("Qb","q","Na",g.ep[2].."s",g.ep[2].."0",g.ph[2].."F","VSB")) 
aF(12, 8, "Cox="..g.ep[2].."ox*"..g.ep[2].."0/tox", U("Cox",g.ep[2].."ox",g.ep[2].."0","tox")) 
aF(12, 8, "f=1/Cox*sqrt(2*q*Na*"..g.ep[2].."s*"..g.ep[2].."0)", U("Cox","q","Na",g.ep[2].."s",g.ep[2].."0")) 
aF(12, 8, "VT0="..g.ph[2].."GC-2*"..g.ph[2].."F-Qb0/Cox-Qox/Cox", U("VT0",g.ph[2].."GC",g.ph[2].."F","Qb0","Cox","Qox")) 

sCat(12, 9, "MOS Transistor II", "") 
aF(12, 9, "kn1="..g.mu[2].."n*Cox", U("kn1",g.mu[2].."n","Cox")) 
aF(12, 9, "kn1="..g.mu[2].."n*"..g.ep[2].."ox*"..g.ep[2].."0/tox", U("kn1",g.mu[2].."n",g.ep[2].."ox",g.ep[2].."0","tox")) 
aF(12, 9, "kn=kn1*W/L", U("kn","kn1","W","L")) 
aF(12, 9, "IDmod=kn/2*(VGS-VT)^2*(1+"..utf8(137).."*VDS)", U("IDmod","kn","VGS","VT","VDS")) 
aF(12, 9, "ID=when(VGS-VT"..utf8(156).."VDS,kn/2*(2*(VGS-VT)*VDS-VDS^2),kn/2*(VGS-VT)^2)", U("ID","VGS","VT","VDS","kn")) 
aF(12, 9, "VT=VT0+f*(sqrt(abs(-2*"..g.ph[2].."F+VSB))-sqrt(2*"..g.ph[2].."F))", U("VT","VT0",g.ph[2].."F","VSB")) 
aF(12, 9, "gm=kn*(VGS-VT)", U("gm","kn","VGS","VT")) 
aF(12, 9, "Ttr=4/3*L^2/("..g.mu[2].."n*(VGS-VT))", U("Ttr","L",g.mu[2].."n","VGS","VT")) 
aF(12, 9, "ffmax=gm/(2*"..g.pi[2].."*Cox*W*L)", U("ffmax","gm","Cox","W","L")) 
aF(12, 9, "gd=kn*(VGS-VT)", U("gd","kn","VGS","VT")) 

sCat(12, 10, "MOS Inverter (Resistive Load)", "") 
aF(12, 10, "kD="..g.mu[2].."n*Cox*WD/LD", U("kD",g.mu[2].."n","Cox","WD","LD")) 
aF(12, 10, "VOH=VDD", U("VOH","VDD")) 
aF(12, 10, "VOL^2-2*(1/(kD*Rl)+VDD-VT)*VOL+2*VDD/(kD*Rl)=0", U("VOL","kD","Rl","VDD","VT")) 
aF(12, 10, "kD/2*(2*(VIH-VT)*Vo-Vo^2)=(VDD-Vo)/Rl", U("kD","VIH","VT","Vo","VDD","Rl")) 
aF(12, 10, "kD/2*(VM-VT)^2=(VDD-VM)/Rl", U("kD","VM","VT","VDD","Rl")) 

sCat(12, 11, "MOS Inverter (Saturated Load)", "") 
aF(12, 11, "kL="..g.mu[2].."n*Cox*WL/LL", U("kL",g.mu[2].."n","Cox","WL","LL")) 
aF(12, 11, "kD="..g.mu[2].."n*Cox*WD/LD", U("kD",g.mu[2].."n","Cox","WD","LD")) 
aF(12, 11, "KR=kD/kL", U("KR","kD","kL")) 
aF(12, 11, "VOH=VDD-(VT0+f*(sqrt(VOH+2*"..g.ph[2].."F)-sqrt(2*"..g.ph[2].."F)))", U("VOH","VDD","VT0",g.ph[2].."F")) 
aF(12, 11, "KR*(2*(Vin-VTD)*Vo-Vo^2)=(VDD-Vo-VTL)^2", U("KR","Vin","VTD","Vo","VDD","VTL")) 
aF(12, 11, "VTL=VT0+f*(sqrt(Vo+2*"..g.ph[2].."F)-sqrt(2*"..g.ph[2].."F))", U("VTL","VT0","Vo",g.ph[2].."F")) 
aF(12, 11, "VIH=(2*(VDD-VTL))/(sqrt(3*KR)+1)+VT0", U("VIH","VDD","VTL","KR","VT0")) 
aF(12, 11, "Vo=(VDD-VTL+VT0+VT0*sqrt(KR))/(1+sqrt(KR))", U("Vo","VDD","VTL","VT0","KR")) 
aF(12, 11, "gmL=kL*(VDD-VTL)", U("gmL","kL","VDD","VTL")) 
aF(12, 11, g.ta[2].."L=CL/gmL", U(g.ta[2].."L","CL","gmL")) 
aF(12, 11, "tch="..g.ta[2].."L*(V1/Vo-1)", U("tch",g.ta[2].."L","V1","Vo")) 
aF(12, 11, g.ta[2].."D=CL/(kD*(V1-VT0))", U(g.ta[2].."D","CL","kD","V1","VT0")) 
aF(12, 11, "tdis="..g.ta[2].."D*((2*VTD)/(V1-VTD)+ln(2*(V1-VTD)/Vo-1))", U("tdis",g.ta[2].."D","VTD","V1","Vo")) 

sCat(12, 12, "MOS Inverter (Depletion Load)", "") 
aF(12, 12, "kL="..g.mu[2].."n*Cox*WL/LL", U("kL",g.mu[2].."n","Cox","WL","LL")) 
aF(12, 12, "kD="..g.mu[2].."n*Cox*WD/LD", U("kD",g.mu[2].."n","Cox","WD","LD")) 
aF(12, 12, "kD/2*(2*(VOH-VT0)*VOL-VOL^2)=kL/2*VTL^2", U("kD","VOH","VT0","VOL","kL","VTL")) 
aF(12, 12, "VTL=VTL0+f*(sqrt(Vo+2*"..g.ph[2].."F)-sqrt(2*"..g.ph[2].."F))", U("VTL","VTL0","Vo",g.ph[2].."F")) 
aF(12, 12, "tch=CL*VL/I0", U("tch","CL","VL","I0")) 
aF(12, 12, "I0=kL*VTL^2", U("I0","kL","VTL")) 

sCat(12, 13, "CMOS Transistor Pair", "") 
aF(12, 13, "kP="..g.mu[2].."p*Cox*WP/lP", U("kP",g.mu[2].."p","Cox","WP","lP")) 
aF(12, 13, "kN="..g.mu[2].."n*Cox*WN/lNN", U("kN",g.mu[2].."n","Cox","WN","lNN")) 
aF(12, 13, "VIH=2*Vo+VTN+(kP/kN)*(VDD-abs(VTP))/(1+kP/kN)", U("VIH","Vo","VTN","kP","kN","VDD","VTP")) 
aF(12, 13, "VIL=(2*Vo-VDD-VTP+kN/kP*VTN)/(1+kN/kP)", U("VIL","Vo","VDD","VTP","kN","kP","VTN")) 
aF(12, 13, "kN/2*(Vin-VTN)^2=kP/2*(VDD-Vin-abs(VTP))^2", U("kN","Vin","VTN","kP","VDD","VTP")) 

sCat(12, 14, "Junction FET", "") 
aF(12, 14, "ID=2*q*Z*"..g.mu[2].."n*Nd*b/L*(VDD-2/3*(Vbi-Vp)*(((VDD+Vbi-VG)/(Vbi-Vp))^1.5-((Vbi-VG)/(Vbi-Vp))^1.5))", U("ID","q","Z",g.mu[2].."n","Nd","b","L","VDD","Vbi","Vp","VG")) 
aF(12, 14, "IDsat=2*q*Z*"..g.mu[2].."n*Nd*b/L*(VDsat-2/3*(Vbi-Vp)*(((VDD+Vbi-VG)/(Vbi-Vp))^1.5-((Vbi-VG)/(Vbi-Vp))^1.5))", U("IDsat","q","Z",g.mu[2].."n","Nd","b","L","VDsat","Vbi","Vp","VDD","VG")) 
aF(12, 14, "b=sqrt(2*"..g.ep[2].."0*"..g.ep[2].."s/(q*Nd)*(Vbi+VDsat-VG))", U("b",g.ep[2].."0",g.ep[2].."s","q","Nd","Vbi","VDsat","VG")) 
aF(12, 14, "VDsat=VG-Vp", U("VDsat","VG","Vp")) 
aF(12, 14, "IDsat=ID0*(1-VG/Vp)^2", U("IDsat","ID0","VG","Vp")) 


Cat(13, "Linear Amplifiers", "") 

CatVar(13, g.al[2].."0", "Current gain, CE", "unitless")
CatVar(13, "Ac", "Common mode gain", "unitless")
CatVar(13, "Ad", "Differential mode gain", "unitless")
CatVar(13, "Ai", "Current gain, CB", "unitless")
CatVar(13, "Aov", "Overall voltage gain", "unitless")
CatVar(13, "Av", "Voltage gain, CC/CD", "unitless")
CatVar(13, g.be[2].."0", "Current gain, CB", "unitless")
CatVar(13, "CMRR", "Common mode reject ratio", "unitless")
CatVar(13, "gm", "Transconductance", "S")
CatVar(13, g.mu[2], "Amplification factor", "unitless")
CatVar(13, "rb", "Base resistance", g.omg[1])
CatVar(13, "rrc", "Collector resistance", g.omg[1])
CatVar(13, "rd", "Drain resistance", g.omg[1])
CatVar(13, "re", "Emitter resistance", g.omg[1])
CatVar(13, "RBA", "External base resistance", g.omg[1])
CatVar(13, "RCA", "External collector resistance", g.omg[1])
CatVar(13, "RDA", "External drain resistance", g.omg[1])
CatVar(13, "REA", "External emitter resistance", g.omg[1])
CatVar(13, "RG", "External gate resistance", g.omg[1])
CatVar(13, "Ric", "Common mode input resistance", g.omg[1])
CatVar(13, "Rid", "Differential input resistance", g.omg[1])
CatVar(13, "Rin", "Input resistance", g.omg[1])
CatVar(13, "Rl", "Load resistance", g.omg[1])
CatVar(13, "Ro", "Output resistance", g.omg[1])
CatVar(13, "Rs", "Source resistance", g.omg[1])

sCat(13, 1, "BJT (Common Base)", "") 
aF(13, 1, g.be[2].."0="..g.al[2].."0/(1-"..g.al[2].."0)", U(g.be[2].."0",g.al[2].."0")) 
aF(13, 1, "Rin=re+rb/"..g.be[2].."0", U("Rin","re","rb",g.be[2].."0")) 
aF(13, 1, "Ro=rrc", U("Ro","rrc")) 
aF(13, 1, "Ai="..g.al[2].."0", U("Ai",g.al[2].."0")) 
aF(13, 1, "Av="..g.al[2].."0*Rl/(re+rb/"..g.be[2].."0)", U("Av",g.al[2].."0","Rl","re","rb",g.be[2].."0")) 
aF(13, 1, "Aov=("..g.al[2].."0*rrc)*(Rin/(Rin+Rs))/(re+rb/"..g.be[2].."0)", U("Aov",g.al[2].."0","rrc","Rin","Rs","re","rb",g.be[2].."0")) 

sCat(13, 2, "BJT (Common Emitter)", "") 
aF(13, 2, g.be[2].."0="..g.al[2].."0/(1-"..g.al[2].."0)", U(g.be[2].."0",g.al[2].."0")) 
aF(13, 2, "Rin=rb+"..g.be[2].."0*re", U("Rin","rb",g.be[2].."0","re")) 
aF(13, 2, "Ro=rrc", U("Ro","rrc")) 
aF(13, 2, "Ai=-"..g.be[2].."0", U("Ai",g.be[2].."0")) 
aF(13, 2, "Av=-"..g.be[2].."0*Rl/("..g.be[2].."0*re+rb)", U("Av",g.be[2].."0","Rl","re","rb")) 
aF(13, 2, "Aov=-"..g.be[2].."0*Rl/(Rs+Rin)", U("Aov",g.be[2].."0","Rl","Rs","Rin")) 

sCat(13, 3, "BJT (Common Collector)", "") 
aF(13, 3, g.be[2].."0="..g.al[2].."0/(1-"..g.al[2].."0)", U(g.be[2].."0",g.al[2].."0")) 
aF(13, 3, "Rin=rb+"..g.be[2].."0*re+("..g.be[2].."0+1)*Rl", U("Rin","rb",g.be[2].."0","re","Rl")) 
aF(13, 3, "Ro=re+(Rs+rb)/"..g.be[2].."0", U("Ro","re","Rs","rb",g.be[2].."0")) 
aF(13, 3, "Ai=rrc/(rrc*(1-"..g.al[2].."0)+Rl+re)", U("Ai","rrc",g.al[2].."0","Rl","re")) 
aF(13, 3, "Av="..g.al[2].."0*Rl/(re+Rl)", U("Av",g.al[2].."0","Rl","re")) 
aF(13, 3, "Aov=("..g.be[2].."0+1)*Rl/(Rs+Rin+("..g.be[2].."0+1)*Rl)", U("Aov",g.be[2].."0","Rl","Rs","Rin")) 

sCat(13, 4, "FET (Common Gate)", "") 
aF(13, 4, g.mu[2].."=gm*rd", U(g.mu[2],"gm","rd")) 
aF(13, 4, "Rin=(Rl+rd)/("..g.mu[2].."+1)", U("Rin","Rl","rd",g.mu[2])) 
aF(13, 4, "Av=("..g.mu[2].."+1)*Rl/(rd+Rl)", U("Av",g.mu[2],"Rl","rd")) 
aF(13, 4, "Ro=rd+("..g.mu[2].."+1)*RG", U("Ro","rd",g.mu[2],"RG")) 

sCat(13, 5, "FET (Common Source)", "") 
aF(13, 5, g.mu[2].."=gm*rd", U(g.mu[2],"gm","rd")) 
aF(13, 5, "Rin=(Rl+rd)/("..g.mu[2].."+1)", U("Rin","Rl","rd",g.mu[2])) 
aF(13, 5, "Av=-gm*(rd*Rl/(rd+Rl))", U("Av","gm","rd","Rl")) 
aF(13, 5, "Ro=rd", U("Ro","rd")) 

sCat(13, 6, "FET (Common Drain)", "") 
aF(13, 6, g.mu[2].."=gm*rd", U(g.mu[2],"gm","rd")) 
aF(13, 6, "Rin=(Rl+rd)/("..g.mu[2].."+1)", U("Rin","Rl","rd",g.mu[2])) 
aF(13, 6, "Av="..g.mu[2].."*Rl/(("..g.mu[2].."+1)*Rl+rd)", U("Av",g.mu[2],"Rl","rd")) 
aF(13, 6, "Ro=rd/("..g.mu[2].."+1)", U("Ro","rd",g.mu[2])) 

sCat(13, 7, "Darlington (CC-CC)", "") 
aF(13, 7, "Rin="..g.be[2].."0*(re+"..g.be[2].."0*(re+Rl))", U("Rin",g.be[2].."0","re","Rl")) 
aF(13, 7, "Ro=re+("..g.be[2].."0*(re+rb)+Rs)/"..g.be[2].."0^2", U("Ro","re",g.be[2].."0","rb","Rs")) 
aF(13, 7, "Ai="..g.be[2].."0^2*RBA/(RBA+"..g.be[2].."0*(Rl+re))", U("Ai",g.be[2].."0","RBA","Rl","re")) 

sCat(13, 8, "Darlington (CC-CE)", "") 
aF(13, 8, "Rin=rb+"..g.be[2].."0*re", U("Rin","rb",g.be[2].."0","re")) 
aF(13, 8, "Ro=rrc/"..g.be[2].."0", U("Ro","rrc",g.be[2].."0")) 
aF(13, 8, "Av=-Rl/(re+Rs/"..g.be[2].."0^2)", U("Av","Rl","re","Rs",g.be[2].."0")) 

sCat(13, 9, "Emitter-Coupled Amplifier", "") 
aF(13, 9, g.be[2].."0="..g.al[2].."0/(1-"..g.al[2].."0)", U(g.be[2].."0",g.al[2].."0")) 
aF(13, 9, "Av=Rl*("..g.be[2].."0/(2*"..g.be[2].."0*re+Rl))", U("Av","Rl",g.be[2].."0","re")) 
aF(13, 9, "Ai=-"..g.al[2].."0*"..g.be[2].."0", U("Ai",g.al[2].."0",g.be[2].."0")) 
aF(13, 9, "Rin="..g.be[2].."0*re+rb", U("Rin",g.be[2].."0","re","rb")) 
aF(13, 9, "Ro=rrc", U("Ro","rrc")) 

sCat(13, 10, "Differential Amplifier", "") 
aF(13, 10, "Ad=-1/2*gm*RCA", U("Ad","gm","RCA")) 
aF(13, 10, "Ac=-"..g.al[2].."0*RCA/(2*REA+re)", U("Ac",g.al[2].."0","RCA","REA","re")) 
aF(13, 10, "Rid=2*(rb+"..g.be[2].."0*re)", U("Rid","rb",g.be[2].."0","re")) 
aF(13, 10, "Ric="..g.be[2].."0*REA", U("Ric",g.be[2].."0","REA")) 

sCat(13, 11, "Source-Coupled JFET Pair", "") 
aF(13, 11, "Ad=-1/2*gm*(rd*RDA)/(rd+RDA)", U("Ad","gm","rd","RDA")) 
aF(13, 11, "Ac=-"..g.mu[2].."*RDA/(("..g.mu[2].."+1)*2*Rs+rd+RDA)", U("Ac",g.mu[2],"RDA","Rs","rd")) 
aF(13, 11, g.mu[2].."=gm*rd", U(g.mu[2],"gm","rd")) 
aF(13, 11, "CMRR=gm*Rs", U("CMRR","gm","Rs")) 


Cat(14, "Class A, B and C Amplifiers", "") 

CatVar(14, "gm", "Transconductance", "S")
CatVar(14, "hFE", "CE current gain", "unitless")
CatVar(14, "hOE", "CE output conductance", "S")
CatVar(14, "I", "Current", "A")
CatVar(14, "IB", "Base current", "A")
CatVar(14, "IC", "Collector Current", "A")
CatVar(14, "dIC", "Current swing from operating pt.", "A")
CatVar(14, "ICBO", "Collector current EB open", "A")
CatVar(14, "ICQ", "Current at operating point", "A")
CatVar(14, "Idc", "DC current", "A")
CatVar(14, "Imax", "Maximum current", "A")
CatVar(14, "K", "Constant", "unitless")
CatVar(14, "m", "Constant", "1/K")
CatVar(14, utf8(962), "Efficiency", "unitless")
CatVar(14, "n", "Turns ratio", "unitless")
CatVar(14, "N1","# turns in primary", "unitless")
CatVar(14, "N2","# turns in secondary", "unitless")
CatVar(14, "Pd", "Power dissipated", "W")
CatVar(14, "Pdc", "DC power input to amp", "W")
CatVar(14, "Po", "Power output", "W")
CatVar(14, "PP", "Compliance", "V")
CatVar(14, "Q", "Quality factor", "unitless")
CatVar(14, g.th[2].."JA", "Thermal resistance", "W/K")--the unit for thermal resistance is K/W, the current unit is for thermal conductance
CatVar(14, "R", "Equivalent resistance", g.omg[1])
CatVar(14, "Rl", "Load resistance", g.omg[1])
CatVar(14, "RR0", "Internal circuit loss", g.omg[1])
CatVar(14, "RR2", "Load resistance", g.omg[1])
CatVar(14, "RB", "External base resistance", g.omg[1])
CatVar(14, "Rrc", "Coupled load resistance", g.omg[1])
CatVar(14, "Rxt", "External emitter resistance", g.omg[1])
CatVar(14, "S", "Instability factor", "unitless")
CatVar(14, "TA", "Ambient temperature", "K")
CatVar(14, "TJ", "Junction temperature", "K")
CatVar(14, "dTj", "Change in temperature", "K")
CatVar(14, "V0", "Voltage across tank circuit", "V")
CatVar(14, "V1", "Voltage across tuned circuit", "V")
CatVar(14, "VBE", "Base emitter voltage", "V")
CatVar(14, "VCC", "Collector supply voltage", "V")
CatVar(14, "dVCE", "Voltage swing from operating pt.", "V")
CatVar(14, "VCEmx", "Maximum transistor rating", "V")
CatVar(14, "VCEmn", "Minimum transistor rating", "V")
CatVar(14, "Vm", "Maximum amplitude", "V")
CatVar(14, "VPP", "Peak-peak volts, secondary", "V")
CatVar(14, "XXC", "Tuned circuit parameter", g.omg[1])
CatVar(14, "XC1", g.pi[2].." equivalent circuit parameter", g.omg[1])
CatVar(14, "XC2", g.pi[2].." equivalent circuit parameter", g.omg[1])
CatVar(14, "XL", g.pi[2].." series reactance", g.omg[1])

sCat(14, 1, "Class A Amplifier", "") 
aF(14, 1, "R=n^2*Rl", U("R","n","Rl")) 
aF(14, 1, "dIC=dVCE/R", U("dIC","dVCE","R")) 
aF(14, 1, "Imax=ICQ+dIC", U("Imax","ICQ","dIC")) 
aF(14, 1, "Pdc=VCC*ICQ", U("Pdc","VCC","ICQ")) 
aF(14, 1, "PP=VCEmx-VCEmn", U("PP","VCEmx","VCEmn")) 
aF(14, 1, "VPP=n*PP", U("VPP","n","PP")) 
aF(14, 1, "Po=(dIC)^2*R/8", U("Po","dIC","R")) 
aF(14, 1, "x=Po/Pdc", U("Po","Pdc"))

sCat(14, 2, "Power Transistor", "") 
aF(14, 2, "TJ=TA+"..g.th[2].."JA*Pd", U("TJ","TA",g.th[2].."JA","Pd")) 
aF(14, 2, "IC=hFE*IB+(1+hFE)*ICBO", U("IC","hFE","IB","ICBO")) 
aF(14, 2, "IB=-(IC*Rxt-VBE)/(Rxt+RB)", U("IB","IC","Rxt","VBE","RB")) 
aF(14, 2, "IC=-hFE*VBE/(hFE*Rxt+RB)+hFE*(Rxt+RB)/(hFE*Rxt+RB)*ICBO", U("IC","hFE","VBE","Rxt","RB","ICBO")) 
aF(14, 2, "S=(1+RB/Rxt)*hFE/(hFE+RB/Rxt)", U("S","RB","Rxt","hFE")) 
aF(14, 2, "IC=-hFE*IB+S*ICBO*(1+m*dTj)", U("IC","hFE","IB","S","ICBO","m","dTj")) 

sCat(14, 3, "Push-Pull Principle", "") 
aF(14, 3, "R=VCC/Imax", U("R","VCC","Imax")) 
aF(14, 3, "Po=VCC^2/(2*R)", U("Po","VCC","R")) 
aF(14, 3, "Po=(N2/(2*N1))^2*VCC^2/(2*RR2)", U("Po","N2","N1","VCC","RR2")) 

sCat(14, 4, "Class B Amplifier", "") 
aF(14, 4, "Po=K^2*VCC^2/(2*R)", U("Po","K","VCC","R")) 
aF(14, 4, "Idc=2*K*Imax/"..g.pi[2], U("Idc","K","Imax",g.pi[2])) 
aF(14, 4, "Pdc=2*K*Imax*VCC/"..g.pi[2], U("Pdc","K","Imax","VCC",g.pi[2])) 
aF(14, 4, "Pdc=2*K*VCC^2/("..g.pi[2].."*R)", U("Pdc","K","VCC","R")) 
aF(14, 4, "x=Po/Pdc", U("Po","Pdc")) 
aF(14, 4, "x="..g.pi[2].."*K/4", U(g.pi[2],"K")) 
aF(14, 4, "Pd=2*VCC^2/("..g.pi[2].."*R)*(K-K^2*"..g.pi[2].."/4)", U("Pd","VCC","R","K")) 
aF(14, 4, "V1=gm*Rl*Vm/(2*sqrt(2))*(1/(1+hOE*Rl/2))", U("V1","gm","Rl","Vm","hOE")) 
aF(14, 4, "IC=gm*Vm/"..g.pi[2].."*(1/(1+hOE*Rl/2))", U("IC","gm","Vm","hOE","Rl")) 

sCat(14, 5, "Class C Amplifier", "") 
aF(14, 5, "x=I^2*Rrc/(I^2*(Rrc+RR0))", U("I","Rrc","RR0")) 
aF(14, 5, "XXC=V0^2/(Q*Po)", U("XXC","V0","Q","Po")) 
aF(14, 5, "XL=XXC*Q^2/(Q^2+1)", U("XL","XXC","Q")) 
aF(14, 5, "XC1=-Rl/Q", U("XC1","Rl","Q")) 
aF(14, 5, "XL=1/Q*(Rl+sqrt(Rl*RR2))", U("XL","Q","Rl","RR2")) 
aF(14, 5, "XC2=-RR2/Q", U("XC2","RR2","Q")) 


Cat(15, "Transformers", "") 

CatVar(15, "I1", "Primary current", "A")
CatVar(15, "I2", "Secondary current", "A")
CatVar(15, "N1","# primary turns", "unitless")
CatVar(15, "N2","# secondary turns", "unitless")
CatVar(15, "RR1", "Primary resistance", g.omg[1])
CatVar(15, "RR2", "Secondary resistance", g.omg[1])
CatVar(15, "Rin", "Equiv. primary resistance", g.omg[1])
CatVar(15, "Rl", "Resistive part of load", g.omg[1])
CatVar(15, "V1", "Primary voltage", "V")
CatVar(15, "V2", "Secondary voltage", "V")
CatVar(15, "XX1", "Primary reactance", g.omg[1])
CatVar(15, "XX2", "Secondary reactance", g.omg[1])
CatVar(15, "Xin", "Equivalent primary reactance", g.omg[1])
CatVar(15, "Xl", "Reactive part of load", g.omg[1])
CatVar(15, "Zin", "Primary impedance", g.omg[1])
CatVar(15, "ZL", "Secondary load", g.omg[1])

sCat(15, 1, "Ideal Transformer", "") 
aF(15, 1, "V1/V2=N1/N2", U("V1","V2","N1","N2")) 
aF(15, 1, "I1*N1=I2*N2", U("I1","N1","I2","N2")) 
aF(15, 1, "V1*I1=V2*I2", U("V1","I1","V2","I2")) 
aF(15, 1, "Zin=(N1/N2)^2*ZL", U("Zin","N1","N2","ZL")) 

sCat(15, 2, "Linear Equivalent Circuit", "") 
aF(15, 2, "V1=N1/N2*V2", U("V1","N1","N2","V2")) 
aF(15, 2, "I1=I2*N2/N1", U("I1","I2","N2","N1")) 
aF(15, 2, "Rin=RR1+(N1/N2)^2*(RR2+Rl)", U("Rin","RR1","N1","N2","RR2","Rl")) 
aF(15, 2, "Xin=XX1+(N1/N2)^2*(XX2+Xl)", U("Xin","XX1","N1","N2","XX2","Xl")) 


Cat(16, "Motors and Generators", "") 

CatVar(16, "A", "Area", "m2")
CatVar(16, "ap","# parallel paths", "unitless")
CatVar(16, "B", "Magnetic induction", "T")
CatVar(16, "Ea", "Average emf induced in armature", "V")
CatVar(16, "Ef", "Field voltage", "V")
CatVar(16, "Ema", "Phase voltage", "V")
CatVar(16, "Es", "Induced voltage", "V")
CatVar(16, "Eta", "Average emf induced per turn", "V")
CatVar(16, "F", "Magnetic pressure", "Pa")
CatVar(16, "H", "Magnetic field intensity", "A/m")
CatVar(16, "Ia", "Armature current", "A")
CatVar(16, "IIf", "Field current", "A")
CatVar(16, "IL", "Load current", "A")
CatVar(16, "Ir", "Rotor current per phase", "A")
CatVar(16, "Isb", "Backward stator current", "A")
CatVar(16, "Isf", "Forward stator current", "A")
CatVar(16, "K", "Machine constant", "unitless")
CatVar(16, "Kf", "Field coefficient", "A/Wb")
CatVar(16, "KM", "Induction motor constant", "unitless")
CatVar(16, "L", "Length of each turn", "m")
CatVar(16, g.th[2], "Phase delay", "rad")
CatVar(16, "N", "Total # armature coils", "unitless")
CatVar(16, "Ns","# stator coils", "unitless")
CatVar(16, g.rh[2], "Resistivity", g.omg[1].."/m")
CatVar(16, g.ph[2], "Flux", "Wb")
CatVar(16, "p","# poles", "unitless")
CatVar(16, "P", "Power", "W")
CatVar(16, "Pa", "Mechanical power", "W")
CatVar(16, "Pma", "Power in rotor per phase", "W")
CatVar(16, "Pme", "Mechanical power", "W")
CatVar(16, "Pr", "Rotor power per phase", "W")
CatVar(16, "RR1", "Rotor resistance per phase", g.omg[1])
CatVar(16, "Ra", "Armature resistance", g.omg[1])
CatVar(16, "Rd", "Adjustable resistance", g.omg[1])
CatVar(16, "Re", "Ext. shunt resistance", g.omg[1])
CatVar(16, "Rel", "Magnetic reluctance", "A/Wb")
CatVar(16, "Rf", "Field coil resistance", g.omg[1])
CatVar(16, "Rl", "Load resistance", g.omg[1])
CatVar(16, "Rr", "Equivalent rotor resistance", g.omg[1])
CatVar(16, "Rs", "Series field resistance", g.omg[1])
CatVar(16, "Rst", "Stator resistance", g.omg[1])
CatVar(16, "s", "Slip", "unitless")
CatVar(16, "sf", "Slip for forward flux", "unitless")
CatVar(16, "sm", "Maximum slip", "unitless")
CatVar(16, "T", "Internal torque", "N*m")
CatVar(16, "Tb", "Backward torque", "N*m")
CatVar(16, "Tf", "Forward torque", "N*m")
CatVar(16, "Tgmax", "Breakdown torque", "N*m")
CatVar(16, "TL", "Load torque", "N*m")
CatVar(16, "Tloss", "Torque loss", "N*m")
CatVar(16, "Tmmax", "Maximum positive torque", "N*m")
CatVar(16, "TTmax", "Pullout torque", "N*m")
CatVar(16, "Ts", "Shaft torque", "N*m")
CatVar(16, "Va", "Applied voltage", "V")
CatVar(16, "Vf", "Field voltage", "V")
CatVar(16, "Vfs", "Field voltage", "V")
CatVar(16, "Vt", "Terminal voltage", "V")
CatVar(16, g.omg[2].."m", "Mechanical radian frequency", "rad/s")
CatVar(16, g.omg[2].."me", "Electrical radian frequency", "rad/s")
CatVar(16, g.omg[2].."r", "Electrical rotor speed", "rad/s")
CatVar(16, g.omg[2].."s", "Electrical stator speed", "rad/s")
CatVar(16, "Wf", "Magnetic energy", "J")
CatVar(16, "XL", "Inductive reactance", g.omg[1])

sCat(16, 1, "Energy Conversion", "") 
aF(16, 1, "Wf=1/2*H*B*L*A", U("Wf","H","B","L","A")) 
aF(16, 1, "Wf=1/2*Rel*"..g.ph[2].."^2", U("Wf","Rel",g.ph[2])) 
aF(16, 1, "F=B^2/(2*"..g.mu[2].."0)", U("F","B",g.mu[2].."0")) 
aF(16, 1, "Es=Ns*"..g.omg[2].."s*"..g.ph[2].."/sqrt(2)", U("Es","Ns",g.omg[2].."s",g.ph[2])) 

sCat(16, 2, "DC Generator", "") 
aF(16, 2, g.omg[2].."me=p/2*"..g.omg[2].."m", U(g.omg[2].."me","p",g.omg[2].."m")) 
aF(16, 2, "Eta=p/"..g.pi[2].."*"..g.omg[2].."m*"..g.ph[2], U("Eta","p",g.omg[2].."m",g.ph[2])) 
aF(16, 2, "Ea=N/ap*(p/"..g.pi[2]..")*"..g.omg[2].."m*"..g.ph[2], U("Ea","N","ap","p",g.omg[2].."m",g.ph[2])) 
aF(16, 2, "Ea=K*"..g.omg[2].."m*"..g.ph[2], U("Ea","K",g.omg[2].."m",g.ph[2])) 
aF(16, 2, "K=N*p/(ap*"..g.pi[2]..")", U("K","N","p","ap",g.pi[2])) 
aF(16, 2, "T*"..g.omg[2].."m=Ea*Ia+Ef*IIf", U("T",g.omg[2].."m","Ea","Ia","Ef","IIf")) 
aF(16, 2, "T=K*"..g.ph[2].."*Ia", U("T","K",g.ph[2],"Ia")) 
aF(16, 2, "Ra="..g.rh[2].."*N/ap^2*(L/A)", U("Ra",g.rh[2],"N","ap","L","A")) 
aF(16, 2, "Vf=Rf*IIf", U("Vf","Rf","IIf")) 
aF(16, 2, "Vt=K*"..g.omg[2].."m*"..g.ph[2].."-Ra*Ia", U("Vt","K",g.omg[2].."m",g.ph[2],"Ra","Ia")) 
aF(16, 2, "Ts=K*"..g.ph[2].."*Ia+Tloss", U("Ts","K",g.ph[2],"Ia","Tloss")) 

sCat(16, 3, "Separately-Excited DC Generator", "") 
aF(16, 3, "IIf=Vfs/(Re+Rf)", U("IIf","Vfs","Re","Rf")) 
aF(16, 3, "Ea=K*"..g.omg[2].."m*"..g.ph[2], U("Ea","K",g.omg[2].."m",g.ph[2])) 
aF(16, 3, "Vt=IL*Rl", U("Vt","IL","Rl")) 
aF(16, 3, "Vt=Ea-Ra*IL", U("Vt","Ea","Ra","IL")) 
aF(16, 3, "IL=K*"..g.ph[2].."*"..g.omg[2].."m/(Ra+Rl)", U("IL","K",g.ph[2],g.omg[2].."m","Ra","Rl")) 

sCat(16, 4, "DC Shunt Generator", "") 
aF(16, 4, "Ea=K*"..g.omg[2].."m*"..g.ph[2], U("Ea","K",g.omg[2].."m",g.ph[2])) 
aF(16, 4, "Vt=(Re+Rf)*IIf", U("Vt","Re","Rf","IIf")) 
aF(16, 4, "Vt=IL*Rl", U("Vt","IL","Rl")) 
aF(16, 4, "Vt=Ea-Ra*Ia", U("Vt","Ea","Ra","Ia")) 
aF(16, 4, "Ia=IL+IIf", U("Ia","IL","IIf")) 
aF(16, 4, "Ea=Ra*Ia+(Re+Rf)*IIf", U("Ea","Ra","Ia","Re","Rf","IIf")) 

sCat(16, 5, "DC Series Generator", "") 
aF(16, 5, "Ia=IIf", U("Ia","IIf")) 
aF(16, 5, "Vt=Ea-(Ra+Rs)*IL", U("Vt","Ea","Ra","Rs","IL")) 

sCat(16, 6, "Separately-Excited DC Motor", "") 
aF(16, 6, "Vf=Rf*IIf", U("Vf","Rf","IIf")) 
aF(16, 6, "Vt=K*"..g.ph[2].."*"..g.omg[2].."m+Ra*Ia", U("Vt","K",g.ph[2],g.omg[2].."m","Ra","Ia")) 
aF(16, 6, "TL=K*"..g.ph[2].."*Ia-Tloss", U("TL","K",g.ph[2],"Ia","Tloss")) 
aF(16, 6, "Ea=K*"..g.omg[2].."m*"..g.ph[2], U("Ea","K",g.omg[2].."m",g.ph[2])) 
aF(16, 6, "T=K*Ia*"..g.ph[2], U("T","K","Ia",g.ph[2])) 
aF(16, 6, g.omg[2].."m=Vt/(K*"..g.ph[2]..")-Ra*T/(K*"..g.ph[2]..")^2", U(g.omg[2].."m","Vt","K",g.ph[2],"Ra","T")) 
aF(16, 6, "T=Tloss+TL", U("T","Tloss","TL")) 
aF(16, 6, "P=T*"..g.omg[2].."m", U("P","T",g.omg[2].."m")) 

sCat(16, 7, "DC Shunt Motor", "") 
aF(16, 7, "Vt=(Re+Rf)*IIf", U("Vt","Re","Rf","IIf")) 
aF(16, 7, "Vt=K*"..g.ph[2].."*"..g.omg[2].."m+Ra*Ia", U("Vt","K",g.ph[2],g.omg[2].."m","Ra","Ia")) 
aF(16, 7, "TL=K*"..g.ph[2].."*Ia-Tloss", U("TL","K",g.ph[2],"Ia","Tloss")) 
aF(16, 7, "Ea=K*"..g.omg[2].."m*"..g.ph[2], U("Ea","K",g.omg[2].."m",g.ph[2])) 
aF(16, 7, g.omg[2].."m=Vt/(K*"..g.ph[2]..")-(Ra+Rd)*T/(K*"..g.ph[2]..")^2", U(g.omg[2].."m","Vt","K",g.ph[2],"Ra","Rd","T")) 
aF(16, 7, "T=Tloss+TL", U("T","Tloss","TL")) 
aF(16, 7, "T=K*"..g.ph[2].."*Ia", U("T","K",g.ph[2],"Ia")) 

sCat(16, 8, "DC Series Motor", "") 
aF(16, 8, "Vt=K*"..g.ph[2].."*"..g.omg[2].."m+(Ra+Rs+Rd)*IL", U("Vt","K",g.ph[2],g.omg[2].."m","Ra","Rs","Rd","IL")) 
aF(16, 8, "TL=K*"..g.ph[2].."*IL-Tloss", U("TL","K",g.ph[2],"IL","Tloss")) 
aF(16, 8, "Ea=K*"..g.omg[2].."m*"..g.ph[2], U("Ea","K",g.omg[2].."m",g.ph[2])) 
aF(16, 8, "T=K*"..g.ph[2].."*IL", U("T","K",g.ph[2],"IL")) 
aF(16, 8, g.omg[2].."m=Vt/(K*"..g.ph[2]..")-(Ra+Rs+Rd)*T/(K*"..g.ph[2]..")^2", U(g.omg[2].."m","Vt","K",g.ph[2],"Ra","Rs","Rd","T")) 
aF(16, 8, "T=Tloss+TL", U("T","Tloss","TL")) 
aF(16, 8, "K*"..g.ph[2].."=Kf*IL", U("K",g.ph[2],"Kf","IL")) 
aF(16, 8, "T=Kf*IL^2", U("T","Kf","IL")) 

sCat(16, 9, "Permanent Magnet Motor", "") 
aF(16, 9, "Ea=K*"..g.ph[2].."*"..g.omg[2].."m", U("Ea","K",g.ph[2],g.omg[2].."m")) 
aF(16, 9, "T=K*"..g.ph[2].."*Ia", U("T","K",g.ph[2],"Ia")) 
aF(16, 9, "Vt=Ea+Ra*Ia", U("Vt","Ea","Ra","Ia")) 
aF(16, 9, "T=Tloss+TL", U("T","Tloss","TL")) 
aF(16, 9, g.omg[2].."m=Vt/(K*"..g.ph[2]..")-Ra*T/(K*"..g.ph[2]..")^2", U(g.omg[2].."m","Vt","K",g.ph[2],"Ra","T")) 

sCat(16, 10, "Induction Motor I", "") 
aF(16, 10, g.omg[2].."r="..g.omg[2].."s-p/2*"..g.omg[2].."m", U(g.omg[2].."r",g.omg[2].."s","p",g.omg[2].."m")) 
aF(16, 10, "s=1-p/2*("..g.omg[2].."m/"..g.omg[2].."s)", U("s","p",g.omg[2].."m",g.omg[2].."s")) 
aF(16, 10, "Pr/Pma=s", U("Pr","Pma","s")) 
aF(16, 10, g.omg[2].."r=s*"..g.omg[2].."s", U(g.omg[2].."r","s",g.omg[2].."s")) 
aF(16, 10, "Pma=3*Ir*Ema", U("Pma","Ir","Ema")) 
aF(16, 10, "Pme=3*(p/2)*("..g.omg[2].."m/"..g.omg[2].."s)*Pma", U("Pme","p",g.omg[2].."m",g.omg[2].."s","Pma")) 
aF(16, 10, "Pme=T*"..g.omg[2].."m", U("Pme","T",g.omg[2].."m")) 
aF(16, 10, "T=3*(p/2)*(Pma/"..g.omg[2].."s)", U("T","p","Pma",g.omg[2].."s")) 
aF(16, 10, "Pma=Rr*Ir^2+(1-s)/s*Rr*Ir^2", U("Pma","Rr","Ir","s")) 
aF(16, 10, "Pa=(1-s)/s*Rr*Ir^2", U("Pa","s","Rr","Ir")) 
aF(16, 10, "Rr=RR1/KM^2", U("Rr","RR1","KM")) 

sCat(16, 11, "Induction Motor II", "") 
aF(16, 11, "Pma=Rr/s*Ir^2", U("Pma","Rr","s","Ir")) 
aF(16, 11, "T=3/2*(p*Pma/"..g.omg[2].."s)", U("T","p","Pma",g.omg[2].."s")) 
aF(16, 11, "T=3/2*(p/"..g.omg[2].."s)*(Rr/s)*(Va^2/((Rst+Rr/s)^2+XL^2))", U("T","p",g.omg[2].."s","Rr","s","Va","Rst","XL")) 
aF(16, 11, "Tmmax=3/4*(p/"..g.omg[2].."s)*(Va^2/(sqrt(Rst^2+XL^2)+Rst))", U("Tmmax","p",g.omg[2].."s","Va","Rst","XL")) 
aF(16, 11, "sm=Rr/sqrt(Rs^2+XL^2)", U("sm","Rr","Rs","XL")) 
aF(16, 11, "Tgmax=-(3/4)*(p/"..g.omg[2].."s)*(Va^2/(sqrt(Rs^2+XL^2)-Rst))", U("Tgmax","p",g.omg[2].."s","Va","Rs","XL","Rst")) 
aF(16, 11, "Rr=RR1/KM^2", U("Rr","RR1","KM")) 

sCat(16, 12, "Single-Phase Induction Motor", "") 
aF(16, 12, "sf=1-p/2*("..g.omg[2].."m/"..g.omg[2].."s)", U("sf","p",g.omg[2].."m",g.omg[2].."s")) 
aF(16, 12, "Tf=p/2*(1/"..g.omg[2].."s)*(Isf^2*Rr/(2*sf))", U("Tf","p",g.omg[2].."s","Isf","Rr","sf")) 
aF(16, 12, "Tb=-(p/2)*(1/"..g.omg[2].."s)*(Isb^2*Rr/(2*(2-sf)))", U("Tb","p",g.omg[2].."s","Isb","Rr","sf")) 

sCat(16, 13, "Synchronous Machines", "") 
aF(16, 13, g.omg[2].."m=2/p*"..g.omg[2].."s", U(g.omg[2].."m","p",g.omg[2].."s")) 
aF(16, 13, "TTmax=3*(p/2)*(IIf*Va/"..g.omg[2].."s)", U("TTmax","p","IIf","Va",g.omg[2].."s")) 
aF(16, 13, "Pma=Va*Ia*cos("..g.th[2]..")", U("Pma","Va","Ia",g.th[2])) 
aF(16, 13, "T=Pme/"..g.omg[2].."m", U("T","Pme",g.omg[2].."m")) 
aF(16, 13, "T=3*(p/2)*(Pma/"..g.omg[2].."s)", U("T","p","Pma",g.omg[2].."s"))

--Physics(energy)

--Physics(forces)

--Maths(polygons)

--Maths(polyhedrons)

--End of Database--
